export interface SegmentSeed {
  orderIndex: number;
  sourceLanguage: string;
  sourceText: string;
  expectedInterpretation: string;
  keywords: string[];
  topic: string;
  register: string;
  difficulty: string;
  scoringNotes: string;
}

export interface DialogueSeed {
  orderIndex: number;
  title: string;
  topic: string;
  totalWords: number;
  segments: SegmentSeed[];
}

export interface MockTestSeed {
  title: string;
  description: string;
  orderIndex: number;
  dialogues: DialogueSeed[];
}

export const mockTests: MockTestSeed[] = [
  // ─── MOCK TEST 1: Health / Hospital ───────────────────────────────────────
  {
    title: "Mock Test 1 — Health & Hospital",
    description: "Hospital appointment and medical consultation scenarios.",
    orderIndex: 1,
    dialogues: [
      {
        orderIndex: 1,
        title: "Dialogue 1 — GP Referral",
        topic: "health",
        totalWords: 290,
        segments: [
          {
            orderIndex: 1,
            sourceLanguage: "English",
            sourceText: "Good morning. I'm the receptionist at Eastside Medical Centre. How can I help you today?",
            expectedInterpretation: "സുപ്രഭാതം. ഞാൻ ഈസ്റ്റ്‌സൈഡ് മെഡിക്കൽ സെന്ററിലെ റിസപ്ഷനിസ്റ്റ് ആണ്. ഇന്ന് ഞാൻ നിങ്ങൾക്ക് എങ്ങനെ സഹായിക്കാം?",
            keywords: ["Eastside Medical Centre", "receptionist"],
            topic: "health",
            register: "semi-formal",
            difficulty: "easy",
            scoringNotes: "Candidate must render the clinic name correctly and use polite register.",
          },
          {
            orderIndex: 2,
            sourceLanguage: "Malayalam",
            sourceText: "എനിക്ക് ഡോക്ടറെ കാണണം. കഴിഞ്ഞ ഒരാഴ്ചയായി നെഞ്ചുവേദന ഉണ്ട്.",
            expectedInterpretation: "I need to see a doctor. I have been having chest pain for the past one week.",
            keywords: ["doctor", "chest pain", "one week"],
            topic: "health",
            register: "semi-formal",
            difficulty: "easy",
            scoringNotes: "Duration 'one week' and symptom 'chest pain' are critical.",
          },
          {
            orderIndex: 3,
            sourceLanguage: "English",
            sourceText: "I see. Has the pain been constant or does it come and go? And have you had any shortness of breath?",
            expectedInterpretation: "മനസ്സിലായി. വേദന നിരന്തരമാണോ അതോ ഇടയ്ക്കിടെ വരുന്നതാണോ? കൂടാതെ ശ്വാസതടസ്സം ഉണ്ടോ?",
            keywords: ["constant", "shortness of breath"],
            topic: "health",
            register: "semi-formal",
            difficulty: "medium",
            scoringNotes: "Both questions must be rendered. 'Shortness of breath' = ശ്വാസതടസ്സം.",
          },
          {
            orderIndex: 4,
            sourceLanguage: "Malayalam",
            sourceText: "വേദന ഇടയ്ക്കിടെ വരുന്നു. ശ്വാസതടസ്സം ഇല്ല. പക്ഷേ ചിലപ്പോൾ തലകറക്കം തോന്നുന്നു.",
            expectedInterpretation: "The pain comes and goes. There is no shortness of breath. But sometimes I feel dizzy.",
            keywords: ["comes and goes", "dizzy", "shortness of breath"],
            topic: "health",
            register: "semi-formal",
            difficulty: "easy",
            scoringNotes: "Three separate symptoms — all must be rendered.",
          },
          {
            orderIndex: 5,
            sourceLanguage: "English",
            sourceText: "I will book you in to see Dr. Sharma this afternoon at 2:30. Please bring your Medicare card.",
            expectedInterpretation: "ഞാൻ ഇന്ന് ഉച്ചതിരിഞ്ഞ് 2:30ന് ഡോ. ശർമ്മയെ കാണാൻ അപ്പോയിന്റ്മെന്റ് ബുക്ക് ചെയ്യുന്നു. ദയവായി നിങ്ങളുടെ മെഡിക്കെയർ കാർഡ് കൊണ്ടുവരിക.",
            keywords: ["Dr. Sharma", "2:30", "Medicare card"],
            topic: "health",
            register: "semi-formal",
            difficulty: "medium",
            scoringNotes: "Time 2:30 and name Dr. Sharma must be exact. Medicare card is a keyword.",
          },
          {
            orderIndex: 6,
            sourceLanguage: "Malayalam",
            sourceText: "ശരി. ഡോക്ടർ ഹൃദ്രോഗ വിദഗ്ധനെ കൂടി കാണണം എന്ന് പറഞ്ഞിരുന്നു. എന്തെങ്കിലും റഫറൽ ആവശ്യമുണ്ടോ?",
            expectedInterpretation: "Okay. The doctor had said that I should also see a cardiologist. Is a referral required?",
            keywords: ["cardiologist", "referral"],
            topic: "health",
            register: "semi-formal",
            difficulty: "medium",
            scoringNotes: "'Cardiologist' = ഹൃദ്രോഗ വിദഗ്ധൻ. Referral concept must be retained.",
          },
          {
            orderIndex: 7,
            sourceLanguage: "English",
            sourceText: "Yes, a referral letter from your GP is required before you can see a specialist. Dr. Sharma will organise that for you today.",
            expectedInterpretation: "അതെ, ഒരു സ്പെഷ്യലിസ്റ്റിനെ കാണുന്നതിന് മുൻപ് നിങ്ങളുടെ ജിപി ഡോക്ടർ നൽകുന്ന റഫറൽ കത്ത് ആവശ്യമാണ്. ഡോ. ശർമ്മ ഇന്ന് അത് ക്രമീകരിക്കും.",
            keywords: ["referral letter", "GP", "specialist", "Dr. Sharma"],
            topic: "health",
            register: "semi-formal",
            difficulty: "medium",
            scoringNotes: "GP, referral letter, and specialist are all key terms.",
          },
          {
            orderIndex: 8,
            sourceLanguage: "Malayalam",
            sourceText: "നന്ദി. ഞാൻ ഉച്ചതിരിഞ്ഞ് 2:30ന് വരാം. ഇൻഷുറൻസ് ഉണ്ടെങ്കിൽ എന്തെങ്കിലും ഇളവ് ലഭിക്കുമോ?",
            expectedInterpretation: "Thank you. I will come at 2:30 in the afternoon. If I have insurance, will I get any discount?",
            keywords: ["2:30", "insurance", "discount"],
            topic: "health",
            register: "semi-formal",
            difficulty: "easy",
            scoringNotes: "Time 2:30, insurance, discount must all be rendered.",
          },
        ],
      },
      {
        orderIndex: 2,
        title: "Dialogue 2 — Hospital Discharge",
        topic: "health",
        totalWords: 285,
        segments: [
          {
            orderIndex: 1,
            sourceLanguage: "English",
            sourceText: "Hello Mrs. Nair. I'm the discharge nurse. We are ready to send you home today.",
            expectedInterpretation: "ഹലോ ശ്രീമതി നായർ. ഞാൻ ഡിസ്ചാർജ് നഴ്സ് ആണ്. ഇന്ന് നിങ്ങളെ വീട്ടിലേക്ക് അയക്കാൻ ഞങ്ങൾ തയ്യാറാണ്.",
            keywords: ["Mrs. Nair", "discharge nurse", "home"],
            topic: "health",
            register: "semi-formal",
            difficulty: "easy",
            scoringNotes: "Name Mrs. Nair must be included. Discharge concept is central.",
          },
          {
            orderIndex: 2,
            sourceLanguage: "Malayalam",
            sourceText: "ഡോക്ടർ ഏതെങ്കിലും മരുന്ന് കൊടുത്തിട്ടുണ്ടോ? ഞാൻ അത് ഫാർമസിയിൽ നിന്ന് വാങ്ങണമോ?",
            expectedInterpretation: "Has the doctor prescribed any medication? Do I need to buy it from the pharmacy?",
            keywords: ["medication", "prescribed", "pharmacy"],
            topic: "health",
            register: "semi-formal",
            difficulty: "easy",
            scoringNotes: "Prescribed medication and pharmacy are the two key elements.",
          },
          {
            orderIndex: 3,
            sourceLanguage: "English",
            sourceText: "Yes. The doctor has prescribed blood thinners. You must take one tablet each morning with food for 30 days.",
            expectedInterpretation: "അതെ. ഡോക്ടർ ബ്ലഡ് തിന്നേഴ്സ് കുറിച്ചിട്ടുണ്ട്. 30 ദിവസം ഓരോ രാവിലെയും ഭക്ഷണത്തോടൊപ്പം ഒരു ഗുളിക കഴിക്കണം.",
            keywords: ["blood thinners", "one tablet", "morning", "30 days"],
            topic: "health",
            register: "semi-formal",
            difficulty: "hard",
            scoringNotes: "Blood thinners, dosage (one tablet), timing (morning with food), and duration (30 days) all critical.",
          },
          {
            orderIndex: 4,
            sourceLanguage: "Malayalam",
            sourceText: "ഈ മരുന്ന് കഴിക്കുന്ന സമയത്ത് മദ്യം കഴിക്കാൻ പാടില്ലേ?",
            expectedInterpretation: "Is it not allowed to consume alcohol while taking this medication?",
            keywords: ["alcohol", "medication"],
            topic: "health",
            register: "semi-formal",
            difficulty: "easy",
            scoringNotes: "Simple yes/no question framing must be preserved.",
          },
          {
            orderIndex: 5,
            sourceLanguage: "English",
            sourceText: "Correct. Alcohol is strictly prohibited while on blood thinners as it increases the risk of internal bleeding.",
            expectedInterpretation: "ശരിയാണ്. ബ്ലഡ് തിന്നേഴ്സ് കഴിക്കുന്ന സമയത്ത് മദ്യം കർശനമായി നിരോധിച്ചിരിക്കുന്നു, കാരണം ആന്തരിക രക്തസ്രാവ സാദ്ധ്യത കൂടുന്നു.",
            keywords: ["alcohol", "prohibited", "internal bleeding"],
            topic: "health",
            register: "formal",
            difficulty: "hard",
            scoringNotes: "Internal bleeding = ആന്തരിക രക്തസ്രാവം. Strictly prohibited must not be softened.",
          },
          {
            orderIndex: 6,
            sourceLanguage: "Malayalam",
            sourceText: "ശരി. ഫോളോ-അപ്പ് അപ്പോയിന്റ്മെന്റ് ഡോക്ടർ ആരുമായാണ്?",
            expectedInterpretation: "Okay. Which doctor is the follow-up appointment with?",
            keywords: ["follow-up", "appointment"],
            topic: "health",
            register: "semi-formal",
            difficulty: "easy",
            scoringNotes: "Follow-up appointment concept must be clear.",
          },
          {
            orderIndex: 7,
            sourceLanguage: "English",
            sourceText: "Your follow-up is with Dr. Patel at the cardiology clinic in two weeks, on the 15th of March at 10 am.",
            expectedInterpretation: "നിങ്ങളുടെ ഫോളോ-അപ്പ് കാർഡിയോളജി ക്ലിനിക്കിൽ ഡോ. പട്ടേലുമായി രണ്ടാഴ്ചകൾക്ക് ശേഷം, മാർച്ച് 15ന് രാവിലെ 10 മണിക്കാണ്.",
            keywords: ["Dr. Patel", "cardiology", "March 15", "10 am"],
            topic: "health",
            register: "semi-formal",
            difficulty: "hard",
            scoringNotes: "All four: name, specialty, date, time are critical accuracy markers.",
          },
          {
            orderIndex: 8,
            sourceLanguage: "Malayalam",
            sourceText: "ഞാൻ മനസ്സിലാക്കി. ഈ കാർഡ് ഉണ്ടോ? ഇതിൽ ഡോക്ടറുടെ നമ്പർ ഉണ്ടോ?",
            expectedInterpretation: "I understand. Do you have this card? Does it have the doctor's number on it?",
            keywords: ["card", "doctor's number"],
            topic: "health",
            register: "semi-formal",
            difficulty: "easy",
            scoringNotes: "Two questions about the card and phone number.",
          },
        ],
      },
    ],
  },

  // ─── MOCK TEST 2: Housing / Tenancy ───────────────────────────────────────
  {
    title: "Mock Test 2 — Housing & Tenancy",
    description: "Rental disputes, repairs, and tenancy rights.",
    orderIndex: 2,
    dialogues: [
      {
        orderIndex: 1,
        title: "Dialogue 1 — Repair Request",
        topic: "housing",
        totalWords: 295,
        segments: [
          {
            orderIndex: 1,
            sourceLanguage: "English",
            sourceText: "Hello, this is the property manager from Greenleaf Real Estate. I'm calling about your maintenance request.",
            expectedInterpretation: "ഹലോ, ഞാൻ ഗ്രീൻലീഫ് റിയൽ എസ്റ്റേറ്റിലെ പ്രോപ്പർട്ടി മാനേജർ ആണ്. നിങ്ങളുടെ മെയിന്റനൻസ് അഭ്യർത്ഥനയെക്കുറിച്ച് ഞാൻ വിളിക്കുകയാണ്.",
            keywords: ["Greenleaf Real Estate", "property manager", "maintenance request"],
            topic: "housing",
            register: "semi-formal",
            difficulty: "easy",
            scoringNotes: "Agency name and role must be clear.",
          },
          {
            orderIndex: 2,
            sourceLanguage: "Malayalam",
            sourceText: "അതെ, ഞാൻ ഒരു ആഴ്ചയായി ഹോട്ട് വാട്ടർ ഇല്ലെന്ന് ജൂലൈ 3ന് ഒരു അഭ്യർത്ഥന അയച്ചിരുന്നു.",
            expectedInterpretation: "Yes, I had sent a request on July 3rd saying that I have had no hot water for one week.",
            keywords: ["July 3rd", "hot water", "one week"],
            topic: "housing",
            register: "semi-formal",
            difficulty: "medium",
            scoringNotes: "Date July 3 and duration one week are critical.",
          },
          {
            orderIndex: 3,
            sourceLanguage: "English",
            sourceText: "I apologise for the delay. A licensed plumber will visit your property tomorrow between 9 am and 12 pm.",
            expectedInterpretation: "താമസത്തിന് ഞാൻ ക്ഷമ ചോദിക്കുന്നു. ഒരു ലൈസൻസ്ഡ് പ്ലംബർ നാളെ രാവിലെ 9 മണി മുതൽ ഉച്ചയ്ക്ക് 12 മണി വരെ നിങ്ങളുടെ വസ്തുവിൽ വരും.",
            keywords: ["licensed plumber", "tomorrow", "9 am", "12 pm"],
            topic: "housing",
            register: "semi-formal",
            difficulty: "medium",
            scoringNotes: "Time window 9–12 and licensed plumber must be exact.",
          },
          {
            orderIndex: 4,
            sourceLanguage: "Malayalam",
            sourceText: "ഞാൻ ജോലിക്ക് പോകണം. ഒരു കീ ഇടതുതരാൻ കഴിയുമോ? അല്ലെങ്കിൽ ഒരു ഞായറാഴ്ച ആകാൻ കഴിയുമോ?",
            expectedInterpretation: "I need to go to work. Can you leave a key? Or can it be on a Sunday?",
            keywords: ["key", "Sunday", "work"],
            topic: "housing",
            register: "semi-formal",
            difficulty: "easy",
            scoringNotes: "Two alternative requests — both must be rendered.",
          },
          {
            orderIndex: 5,
            sourceLanguage: "English",
            sourceText: "We cannot leave a key for privacy and security reasons. However, we can reschedule for this Saturday between 2 and 4 pm if that suits you.",
            expectedInterpretation: "സ്വകാര്യതയും സുരക്ഷിതത്വവും കാരണം ഞങ്ങൾക്ക് ഒരു കീ ഇടാൻ കഴിയില്ല. എന്നിരുന്നാലും, ഈ ശനിയാഴ്ച ഉച്ചതിരിഞ്ഞ് 2 മുതൽ 4 മണി വരെ നിങ്ങൾക്ക് അനുകൂലമാണെങ്കിൽ ഞങ്ങൾ മാറ്റം ക്രമീകരിക്കാം.",
            keywords: ["privacy", "security", "Saturday", "2 pm", "4 pm"],
            topic: "housing",
            register: "semi-formal",
            difficulty: "hard",
            scoringNotes: "Reason, time window Saturday 2–4 pm, and conditional offer all required.",
          },
          {
            orderIndex: 6,
            sourceLanguage: "Malayalam",
            sourceText: "ശനിയാഴ്ച ശരിയാണ്. ഈ കേടുപാടിനുള്ള ചെലവ് ആര് വഹിക്കും?",
            expectedInterpretation: "Saturday is fine. Who will bear the cost of this repair?",
            keywords: ["Saturday", "cost", "repair"],
            topic: "housing",
            register: "semi-formal",
            difficulty: "easy",
            scoringNotes: "Question about cost responsibility must be clear.",
          },
          {
            orderIndex: 7,
            sourceLanguage: "English",
            sourceText: "The landlord is responsible for all essential repairs under the Residential Tenancies Act. You will not be charged.",
            expectedInterpretation: "റെസിഡൻഷ്യൽ ടെനൻസീസ് ആക്ട് പ്രകാരം എല്ലാ അവശ്യ അറ്റകുറ്റപ്പണികൾക്കും ഭൂവുടമ ഉത്തരവാദിയാണ്. നിങ്ങൾക്ക് ഒരു ചെലവും ഉണ്ടാകില്ല.",
            keywords: ["Residential Tenancies Act", "landlord", "responsible", "essential repairs"],
            topic: "housing",
            register: "formal",
            difficulty: "hard",
            scoringNotes: "Act name, landlord responsibility, and no charge — all three critical.",
          },
          {
            orderIndex: 8,
            sourceLanguage: "Malayalam",
            sourceText: "നന്ദി. ഒരു ലിഖിത സ്ഥിരീകരണം ഇമെയിൽ ആയി അയക്കാൻ കഴിയുമോ?",
            expectedInterpretation: "Thank you. Can you send a written confirmation by email?",
            keywords: ["written confirmation", "email"],
            topic: "housing",
            register: "semi-formal",
            difficulty: "easy",
            scoringNotes: "Written confirmation and email method.",
          },
        ],
      },
      {
        orderIndex: 2,
        title: "Dialogue 2 — Bond Dispute",
        topic: "housing",
        totalWords: 280,
        segments: [
          {
            orderIndex: 1,
            sourceLanguage: "English",
            sourceText: "Good afternoon. I'm calling from the Tenancy Dispute Resolution Service. Is this Mr. Thomas?",
            expectedInterpretation: "ഗുഡ് ആഫ്റ്റർനൂൺ. ഞാൻ ടെനൻസി ഡിസ്പ്യൂട്ട് റെസൊലൂഷൻ സർവ്വീസിൽ നിന്ന് വിളിക്കുകയാണ്. ശ്രീ. തോമസ് ആണോ?",
            keywords: ["Tenancy Dispute Resolution Service", "Mr. Thomas"],
            topic: "housing",
            register: "formal",
            difficulty: "easy",
            scoringNotes: "Service name and person's name must be accurate.",
          },
          {
            orderIndex: 2,
            sourceLanguage: "Malayalam",
            sourceText: "അതെ, ഞാൻ തോമസ് ആണ്. ഞാൻ ബോണ്ട് മണി $1,500 തിരിച്ചുകിട്ടാൻ അഭ്യർത്ഥന നൽകിയിരുന്നു.",
            expectedInterpretation: "Yes, I am Thomas. I had submitted a request to get back the bond money of $1,500.",
            keywords: ["Thomas", "$1,500", "bond money"],
            topic: "housing",
            register: "formal",
            difficulty: "medium",
            scoringNotes: "Amount $1,500 must be exact.",
          },
          {
            orderIndex: 3,
            sourceLanguage: "English",
            sourceText: "Yes. The landlord has claimed $450 for carpet cleaning and $300 for a broken window. Do you dispute these charges?",
            expectedInterpretation: "അതെ. ഭൂവുടമ കാർപ്പറ്റ് ക്ലീനിങ്ങിന് $450ഉം ജനൽ ഉടഞ്ഞതിന് $300ഉം ക്ലൈം ചെയ്തിട്ടുണ്ട്. നിങ്ങൾ ഈ ചാർജുകൾ തർക്കിക്കുന്നുണ്ടോ?",
            keywords: ["$450", "carpet cleaning", "$300", "broken window"],
            topic: "housing",
            register: "formal",
            difficulty: "hard",
            scoringNotes: "Both amounts and both items must be precise.",
          },
          {
            orderIndex: 4,
            sourceLanguage: "Malayalam",
            sourceText: "ജനൽ ഞാൻ ഉടക്കിയിട്ടില്ല. അത് ഞാൻ വന്നപ്പോൾ മുതൽ ഉണ്ടായിരുന്ന കേടാണ്.",
            expectedInterpretation: "I did not break the window. It was damage that existed from when I moved in.",
            keywords: ["window", "damage", "moved in"],
            topic: "housing",
            register: "formal",
            difficulty: "medium",
            scoringNotes: "Pre-existing damage claim must be clear.",
          },
          {
            orderIndex: 5,
            sourceLanguage: "English",
            sourceText: "Do you have any photos or inspection report showing the window was already damaged at the start of tenancy?",
            expectedInterpretation: "ടെനൻസി ആരംഭിക്കുമ്പോൾ ജനൽ ഇതിനകം കേടായിട്ടുണ്ടെന്ന് കാണിക്കുന്ന ഫോട്ടോകൾ അല്ലെങ്കിൽ ഇൻസ്പെക്ഷൻ റിപ്പോർട്ട് നിങ്ങളുടെ കൈവശമുണ്ടോ?",
            keywords: ["photos", "inspection report", "start of tenancy"],
            topic: "housing",
            register: "formal",
            difficulty: "medium",
            scoringNotes: "Evidence types (photos, inspection report) and timing (start of tenancy) are key.",
          },
          {
            orderIndex: 6,
            sourceLanguage: "Malayalam",
            sourceText: "അതെ, ഞാൻ കയറിയ ദിവസം ചിത്രങ്ങൾ എടുത്തിരുന്നു. അവ ഇപ്പോഴും എന്റെ ഫോണിൽ ഉണ്ട്.",
            expectedInterpretation: "Yes, I had taken photos on the day I moved in. They are still on my phone.",
            keywords: ["photos", "moved in", "phone"],
            topic: "housing",
            register: "semi-formal",
            difficulty: "easy",
            scoringNotes: "Photo evidence and timing must be clear.",
          },
          {
            orderIndex: 7,
            sourceLanguage: "English",
            sourceText: "Please upload those photos to our online portal within 7 days. Your case number is TDR-20458.",
            expectedInterpretation: "ദയവായി ആ ഫോട്ടോകൾ 7 ദിവസത്തിനുള്ളിൽ ഞങ്ങളുടെ ഓൺലൈൻ പോർട്ടലിൽ അപ്‌ലോഡ് ചെയ്യുക. നിങ്ങളുടെ കേസ് നമ്പർ TDR-20458 ആണ്.",
            keywords: ["7 days", "online portal", "TDR-20458"],
            topic: "housing",
            register: "formal",
            difficulty: "hard",
            scoringNotes: "Case number TDR-20458 and 7-day deadline are critical.",
          },
          {
            orderIndex: 8,
            sourceLanguage: "Malayalam",
            sourceText: "ഞാൻ മനസ്സിലാക്കി. ഈ കേസ് തീർപ്പ് ആകാൻ എത്ര സമയം ആകും?",
            expectedInterpretation: "I understand. How long will it take for this case to be resolved?",
            keywords: ["case", "resolved", "how long"],
            topic: "housing",
            register: "formal",
            difficulty: "easy",
            scoringNotes: "Question about timeline must be accurately framed.",
          },
        ],
      },
    ],
  },

  // ─── MOCK TEST 3: Employment / Workplace Rights ───────────────────────────
  {
    title: "Mock Test 3 — Employment & Workplace",
    description: "Unfair dismissal, workplace conditions, and Fair Work.",
    orderIndex: 3,
    dialogues: [
      {
        orderIndex: 1,
        title: "Dialogue 1 — Unfair Dismissal Complaint",
        topic: "employment",
        totalWords: 300,
        segments: [
          {
            orderIndex: 1,
            sourceLanguage: "English",
            sourceText: "Hello. You have reached the Fair Work Commission. How can I direct your call?",
            expectedInterpretation: "ഹലോ. നിങ്ങൾ ഫെയർ വർക്ക് കമ്മീഷനിൽ ആണ് എത്തിയിരിക്കുന്നത്. ഞാൻ നിങ്ങളുടെ കോൾ എങ്ങോട്ട് ഡയറക്ട് ചെയ്യണം?",
            keywords: ["Fair Work Commission"],
            topic: "employment",
            register: "formal",
            difficulty: "easy",
            scoringNotes: "Fair Work Commission name is critical.",
          },
          {
            orderIndex: 2,
            sourceLanguage: "Malayalam",
            sourceText: "ഞാൻ അന്യായമായ പിരിച്ചുവിടൽ ആരോപിക്കാൻ ആഗ്രഹിക്കുന്നു. 3 ആഴ്ച മുൻപ് ഞാൻ ജോലി നഷ്ടപ്പെട്ടു.",
            expectedInterpretation: "I would like to lodge an unfair dismissal claim. I lost my job 3 weeks ago.",
            keywords: ["unfair dismissal", "3 weeks"],
            topic: "employment",
            register: "formal",
            difficulty: "medium",
            scoringNotes: "Unfair dismissal and 3 weeks are both critical.",
          },
          {
            orderIndex: 3,
            sourceLanguage: "English",
            sourceText: "I'm sorry to hear that. Please note that the deadline to lodge an unfair dismissal application is 21 days from termination.",
            expectedInterpretation: "അത് കേട്ടതിൽ ഖേദം. ദയവായി ശ്രദ്ധിക്കുക, അൺഫെയർ ഡിസ്മിസൽ അപ്ലിക്കേഷൻ ഫയൽ ചെയ്യാനുള്ള അവസാന തീയതി ജോലി ഒഴിവാക്കൽ നടന്ന ദിനം മുതൽ 21 ദിവസമാണ്.",
            keywords: ["21 days", "termination", "unfair dismissal"],
            topic: "employment",
            register: "formal",
            difficulty: "hard",
            scoringNotes: "21-day deadline from termination is a critical legal fact.",
          },
          {
            orderIndex: 4,
            sourceLanguage: "Malayalam",
            sourceText: "ഞാൻ ഇനിയും ആ സമയ പരിധിക്ക് ഉള്ളിൽ ആണ്. ഇപ്പോൾ ഒരു ജോലി ഉണ്ടോ ആണോ?",
            expectedInterpretation: "I am still within that time limit. Do I need to be employed right now?",
            keywords: ["time limit", "employed"],
            topic: "employment",
            register: "formal",
            difficulty: "easy",
            scoringNotes: "Both assertions must be rendered clearly.",
          },
          {
            orderIndex: 5,
            sourceLanguage: "English",
            sourceText: "No. You do not need to be currently employed. But you must have worked for the employer for at least 6 months to be eligible.",
            expectedInterpretation: "ഇല്ല. നിങ്ങൾ നിലവിൽ ജോലി ചെയ്യുന്നുണ്ടാകണം എന്നില്ല. എന്നാൽ യോഗ്യത നേടുന്നതിന് നിങ്ങൾ ആ തൊഴിലുടമയ്ക്ക് കീഴിൽ ചുരുങ്ങിയത് 6 മാസം ജോലി ചെയ്തിട്ടുണ്ടായിരിക്കണം.",
            keywords: ["6 months", "eligible", "employer"],
            topic: "employment",
            register: "formal",
            difficulty: "hard",
            scoringNotes: "Eligibility criterion (6 months) is critical.",
          },
          {
            orderIndex: 6,
            sourceLanguage: "Malayalam",
            sourceText: "ഞാൻ രണ്ട് വർഷം ജോലി ചെയ്തിട്ടുണ്ട്. ഈ ഫോം ഓൺലൈനിൽ ഫിൽ ചെയ്യാൻ കഴിയുമോ?",
            expectedInterpretation: "I have worked for two years. Can this form be filled in online?",
            keywords: ["two years", "form", "online"],
            topic: "employment",
            register: "semi-formal",
            difficulty: "easy",
            scoringNotes: "Duration two years and online option must be captured.",
          },
          {
            orderIndex: 7,
            sourceLanguage: "English",
            sourceText: "Yes. Visit fairwork.gov.au and complete the F2 Application Form. You will receive a case number by email.",
            expectedInterpretation: "അതെ. fairwork.gov.au സന്ദർശിക്കുക, F2 അപ്ലിക്കേഷൻ ഫോം പൂരിപ്പിക്കുക. ഇമെയിൽ വഴി ഒരു കേസ് നമ്പർ ലഭിക്കും.",
            keywords: ["fairwork.gov.au", "F2", "case number", "email"],
            topic: "employment",
            register: "formal",
            difficulty: "hard",
            scoringNotes: "Website, form number F2, and case number by email — all critical.",
          },
          {
            orderIndex: 8,
            sourceLanguage: "Malayalam",
            sourceText: "ഈ കേസ് കൈകാര്യം ചെയ്യാൻ ഒരു ലേബർ ലോയർ ആവശ്യമാണോ?",
            expectedInterpretation: "Is a labour lawyer required to handle this case?",
            keywords: ["labour lawyer", "case"],
            topic: "employment",
            register: "formal",
            difficulty: "easy",
            scoringNotes: "Labour lawyer concept and question format.",
          },
        ],
      },
      {
        orderIndex: 2,
        title: "Dialogue 2 — Wage Theft Complaint",
        topic: "employment",
        totalWords: 275,
        segments: [
          {
            orderIndex: 1,
            sourceLanguage: "English",
            sourceText: "Good morning. Wage Inspectorate Victoria. My name is Officer Chen. How can I help?",
            expectedInterpretation: "ഗുഡ് മോർണിങ്. വേജ് ഇൻസ്പെക്ടറേറ്റ് വിക്ടോറിയ. എന്റെ പേര് ഓഫീസർ ചെൻ ആണ്. ഞാൻ എങ്ങനെ സഹായിക്കാം?",
            keywords: ["Wage Inspectorate Victoria", "Officer Chen"],
            topic: "employment",
            register: "formal",
            difficulty: "easy",
            scoringNotes: "Organisation name and officer name must both appear.",
          },
          {
            orderIndex: 2,
            sourceLanguage: "Malayalam",
            sourceText: "എന്റെ തൊഴിലുടമ ഒരു മാസമായി ശമ്പളം നൽകിയിട്ടില്ല. കൂടാതെ ഓവർടൈം പേ ഇല്ല.",
            expectedInterpretation: "My employer has not paid salary for one month. Also, there is no overtime pay.",
            keywords: ["one month", "salary", "overtime pay"],
            topic: "employment",
            register: "formal",
            difficulty: "medium",
            scoringNotes: "Two separate complaints — one month and no overtime pay.",
          },
          {
            orderIndex: 3,
            sourceLanguage: "English",
            sourceText: "That is a serious matter. What is the name of your employer and your employment type — casual, part-time, or full-time?",
            expectedInterpretation: "അത് ഗുരുതരമായ ഒരു കാര്യമാണ്. നിങ്ങളുടെ തൊഴിലുടമയുടെ പേര് എന്താണ്, നിങ്ങളുടെ തൊഴിൽ രൂപം — കാഷ്വൽ, പാർട്ട്-ടൈം, അല്ലെങ്കിൽ ഫുൾ-ടൈം — ഏതാണ്?",
            keywords: ["employer name", "casual", "part-time", "full-time"],
            topic: "employment",
            register: "formal",
            difficulty: "medium",
            scoringNotes: "All three employment types must be rendered.",
          },
          {
            orderIndex: 4,
            sourceLanguage: "Malayalam",
            sourceText: "ഞാൻ ഫുൾ-ടൈം ആണ്. തൊഴിലുടമ Sunrise Cleaning Services ആണ്.",
            expectedInterpretation: "I am full-time. The employer is Sunrise Cleaning Services.",
            keywords: ["full-time", "Sunrise Cleaning Services"],
            topic: "employment",
            register: "formal",
            difficulty: "easy",
            scoringNotes: "Company name exact.",
          },
          {
            orderIndex: 5,
            sourceLanguage: "English",
            sourceText: "Under the Fair Work Act, your employer must pay you within 7 days of each pay period. You may also be owed interest on late payments.",
            expectedInterpretation: "ഫെയർ വർക്ക് ആക്ട് പ്രകാരം, തൊഴിലുടമ ഓരോ ശമ്പള കാലയളവും കഴിഞ്ഞ് 7 ദിവസത്തിനുള്ളിൽ നിങ്ങൾക്ക് ശമ്പളം നൽകണം. കൂടാതെ, വൈകിയ പേയ്‌മെന്റുകൾക്ക് പലിശ ലഭ്യമാകാം.",
            keywords: ["Fair Work Act", "7 days", "interest", "late payments"],
            topic: "employment",
            register: "formal",
            difficulty: "hard",
            scoringNotes: "Act name, 7-day rule, and interest on late payments — all critical.",
          },
          {
            orderIndex: 6,
            sourceLanguage: "Malayalam",
            sourceText: "ഈ ആരോപണം ഫയൽ ചെയ്തതിന് ശേഷം എന്നെ ജോലിയിൽ നിന്ന് പുറത്താക്കാൻ കഴിയുമോ?",
            expectedInterpretation: "Can I be dismissed from work after filing this complaint?",
            keywords: ["dismissed", "complaint"],
            topic: "employment",
            register: "formal",
            difficulty: "easy",
            scoringNotes: "Fear of retaliation must be clearly expressed.",
          },
          {
            orderIndex: 7,
            sourceLanguage: "English",
            sourceText: "No. Dismissing or threatening a worker for lodging a complaint is illegal under adverse action provisions.",
            expectedInterpretation: "ഇല്ല. ഒരു ആരോപണം ഫയൽ ചെയ്തതിന് ഒരു ജീവനക്കാരനെ ഒഴിവാക്കുകയോ ഭീഷണിപ്പെടുത്തുകയോ ചെയ്യുന്നത് ആഡ്‌വേഴ്സ് ആക്ഷൻ വ്യവസ്ഥകൾ പ്രകാരം നിയമവിരുദ്ധമാണ്.",
            keywords: ["illegal", "adverse action", "complaint"],
            topic: "employment",
            register: "formal",
            difficulty: "hard",
            scoringNotes: "Adverse action provisions and illegal are critical legal terms.",
          },
          {
            orderIndex: 8,
            sourceLanguage: "Malayalam",
            sourceText: "ഞാൻ മനസ്സിലാക്കി. ഒരു ശമ്പള വ്യതിയാനം ഡോക്യുമെന്റ് ഹാജരാക്കണോ?",
            expectedInterpretation: "I understand. Should I submit a payslip document?",
            keywords: ["payslip", "document", "submit"],
            topic: "employment",
            register: "formal",
            difficulty: "easy",
            scoringNotes: "Payslip submission question.",
          },
        ],
      },
    ],
  },

  // ─── MOCK TEST 4: Legal / Police ──────────────────────────────────────────
  {
    title: "Mock Test 4 — Legal & Police",
    description: "Police interview, court notice, and legal rights.",
    orderIndex: 4,
    dialogues: [
      {
        orderIndex: 1,
        title: "Dialogue 1 — Police Interview",
        topic: "legal",
        totalWords: 295,
        segments: [
          {
            orderIndex: 1,
            sourceLanguage: "English",
            sourceText: "Good afternoon. I am Detective Constable Morris. You are here today to give a statement about an incident on King Street.",
            expectedInterpretation: "ഗുഡ് ആഫ്റ്റർനൂൺ. ഞാൻ ഡിറ്റക്ടിവ് കോൺസ്റ്റബിൾ മോറിസ് ആണ്. കിംഗ് സ്ട്രീറ്റിൽ ഉണ്ടായ ഒരു സംഭവത്തെക്കുറിച്ച് മൊഴി നൽകാൻ നിങ്ങൾ ഇന്ന് ഇവിടെ വന്നിട്ടുണ്ട്.",
            keywords: ["Detective Constable Morris", "King Street", "statement"],
            topic: "legal",
            register: "formal",
            difficulty: "medium",
            scoringNotes: "Rank, name, location, and purpose must be accurate.",
          },
          {
            orderIndex: 2,
            sourceLanguage: "Malayalam",
            sourceText: "ഞാൻ ഒരു സ്വതന്ത്ര സാക്ഷി ആണ്. ഞാൻ ഒരു കോടതിയിലും ഇതുവരെ ഒരു മൊഴിയും നൽകിയിട്ടില്ല.",
            expectedInterpretation: "I am an independent witness. I have never given a statement in any court before.",
            keywords: ["independent witness", "statement", "court"],
            topic: "legal",
            register: "formal",
            difficulty: "easy",
            scoringNotes: "Independent witness and never given statement before.",
          },
          {
            orderIndex: 3,
            sourceLanguage: "English",
            sourceText: "That is fine. This interview is voluntary. You have the right to have a lawyer present if you wish.",
            expectedInterpretation: "കുഴപ്പമില്ല. ഈ അഭിമുഖം ഐഛികമാണ്. നിങ്ങൾ ആഗ്രഹിക്കുന്നെങ്കിൽ ഒരു അഭിഭാഷകൻ ഉണ്ടാകണം എന്ന് ആവശ്യപ്പെടാൻ നിങ്ങൾക്ക് അവകാശം ഉണ്ട്.",
            keywords: ["voluntary", "lawyer", "right"],
            topic: "legal",
            register: "formal",
            difficulty: "medium",
            scoringNotes: "Voluntary nature and right to lawyer are both key legal rights.",
          },
          {
            orderIndex: 4,
            sourceLanguage: "Malayalam",
            sourceText: "ഒരു അഭിഭാഷകൻ ആവശ്യമില്ല. ഞാൻ ആ ദിവസം കിംഗ് സ്ട്രീറ്റിൽ ഉണ്ടായിരുന്നു.",
            expectedInterpretation: "I do not need a lawyer. I was present on King Street that day.",
            keywords: ["lawyer", "King Street"],
            topic: "legal",
            register: "formal",
            difficulty: "easy",
            scoringNotes: "Two assertions — no lawyer needed and was present.",
          },
          {
            orderIndex: 5,
            sourceLanguage: "English",
            sourceText: "Can you describe what you saw at approximately 6:45 pm on Friday the 8th of September?",
            expectedInterpretation: "സെപ്റ്റംബർ 8ാം തീയതി വെള്ളിയാഴ്ച ഏകദേശം വൈകിട്ട് 6:45ന് നിങ്ങൾ കണ്ടതെന്ത് എന്ന് വിവരിക്കാൻ കഴിയുമോ?",
            keywords: ["6:45 pm", "Friday", "September 8"],
            topic: "legal",
            register: "formal",
            difficulty: "hard",
            scoringNotes: "Day, date, and exact time all critical.",
          },
          {
            orderIndex: 6,
            sourceLanguage: "Malayalam",
            sourceText: "ഞാൻ ഒരു നീല കാർ ഒരു മഞ്ഞ കാറിൽ ഇടിക്കുന്നത് കണ്ടു. ഡ്രൈവർ ഓടിപ്പോയി.",
            expectedInterpretation: "I saw a blue car hit a yellow car. The driver ran away.",
            keywords: ["blue car", "yellow car", "driver", "ran away"],
            topic: "legal",
            register: "formal",
            difficulty: "easy",
            scoringNotes: "Colours of both cars and driver fleeing must be exact.",
          },
          {
            orderIndex: 7,
            sourceLanguage: "English",
            sourceText: "Did you notice the registration plate? Even a partial number or letter would be helpful.",
            expectedInterpretation: "നിങ്ങൾ നമ്പർ പ്ലേറ്റ് ശ്രദ്ധിച്ചോ? ഒരു ഭാഗം നമ്പർ അല്ലെങ്കിൽ ഒരു അക്ഷരം കണ്ടാൽ പോലും സഹായകരമാകും.",
            keywords: ["registration plate", "partial number"],
            topic: "legal",
            register: "formal",
            difficulty: "medium",
            scoringNotes: "Registration plate and even partial is helpful — both concepts needed.",
          },
          {
            orderIndex: 8,
            sourceLanguage: "Malayalam",
            sourceText: "ഞാൻ ABC എന്ന് ശ്രദ്ധിച്ചു, ബാക്കി കണ്ടില്ല. ഞാൻ ഇത് ഒരു ലിഖിത മൊഴിയായി നൽകണോ?",
            expectedInterpretation: "I noticed ABC, I did not see the rest. Do I need to provide this as a written statement?",
            keywords: ["ABC", "written statement"],
            topic: "legal",
            register: "formal",
            difficulty: "medium",
            scoringNotes: "Partial plate ABC and written statement question.",
          },
        ],
      },
      {
        orderIndex: 2,
        title: "Dialogue 2 — Court Notice",
        topic: "legal",
        totalWords: 280,
        segments: [
          {
            orderIndex: 1,
            sourceLanguage: "English",
            sourceText: "Hello, this is Community Legal Centre. You mentioned you received a court notice. Can you tell me more?",
            expectedInterpretation: "ഹലോ, ഞാൻ കമ്യൂണിറ്റി ലീഗൽ സെന്ററിൽ നിന്ന് ആണ്. നിങ്ങൾക്ക് ഒരു കോടതി നോട്ടീസ് ലഭിച്ചതായി പറഞ്ഞല്ലോ. കൂടുതൽ വിവരങ്ങൾ പറഞ്ഞ് തരാൻ കഴിയുമോ?",
            keywords: ["Community Legal Centre", "court notice"],
            topic: "legal",
            register: "formal",
            difficulty: "easy",
            scoringNotes: "Organisation name and court notice concept.",
          },
          {
            orderIndex: 2,
            sourceLanguage: "Malayalam",
            sourceText: "ഞാൻ ഒരു ഡിഫോൾട്ട് ജഡ്ജ്‌മെന്റ് നോട്ടീസ് ലഭിച്ചു. $3,200 ക്രെഡിറ്റ് കാർഡ് കടം കാരണം.",
            expectedInterpretation: "I received a default judgment notice. It is because of a credit card debt of $3,200.",
            keywords: ["default judgment", "$3,200", "credit card debt"],
            topic: "legal",
            register: "formal",
            difficulty: "hard",
            scoringNotes: "Default judgment and exact amount $3,200 are both critical.",
          },
          {
            orderIndex: 3,
            sourceLanguage: "English",
            sourceText: "When was the notice issued? You generally have 28 days to respond or apply to set aside the judgment.",
            expectedInterpretation: "നോട്ടീസ് എന്ന് ഇഷ്യൂ ചെയ്തു? സാധാരണ 28 ദിവസത്തിനുള്ളിൽ മറുപടി നൽകുകയോ ജഡ്ജ്‌മെന്റ് റദ്ദ് ചെയ്യാൻ അഭ്യർത്ഥിക്കുകയോ ചെയ്യാം.",
            keywords: ["28 days", "respond", "set aside"],
            topic: "legal",
            register: "formal",
            difficulty: "hard",
            scoringNotes: "28-day deadline and set aside option are critical.",
          },
          {
            orderIndex: 4,
            sourceLanguage: "Malayalam",
            sourceText: "നോട്ടീസ് ഈ ആഴ്ച ലഭിച്ചു. ഞാൻ ഈ കടം അറിഞ്ഞില്ല. ഇത് ഒരു തട്ടിപ്പ് ആകാം.",
            expectedInterpretation: "I received the notice this week. I was not aware of this debt. It may be a fraud.",
            keywords: ["this week", "debt", "fraud"],
            topic: "legal",
            register: "formal",
            difficulty: "medium",
            scoringNotes: "Timing, unawareness of debt, and fraud allegation all needed.",
          },
          {
            orderIndex: 5,
            sourceLanguage: "English",
            sourceText: "In that case you should urgently file for a set aside and attach a statutory declaration explaining fraud.",
            expectedInterpretation: "ആ സ്ഥിതിക്ക്, നിങ്ങൾ അടിയന്തിരമായി ഒരു സെറ്റ് അസൈഡ് ഫയൽ ചെയ്ത് തട്ടിപ്പ് വിശദീകരിക്കുന്ന ഒരു സ്റ്റാറ്റ്യൂട്ടറി ഡിക്ലറേഷൻ ചേർക്കണം.",
            keywords: ["set aside", "statutory declaration", "fraud", "urgently"],
            topic: "legal",
            register: "formal",
            difficulty: "hard",
            scoringNotes: "Legal terms set aside and statutory declaration must be rendered.",
          },
          {
            orderIndex: 6,
            sourceLanguage: "Malayalam",
            sourceText: "ഞാൻ ഒരു ഇൻകം സ്റ്റേറ്റ്‌മെന്റ് ഫോം കൂടി ഫിൽ ചെയ്യേണ്ടതുണ്ടോ?",
            expectedInterpretation: "Do I also need to fill in an income statement form?",
            keywords: ["income statement", "form"],
            topic: "legal",
            register: "formal",
            difficulty: "easy",
            scoringNotes: "Income statement form question.",
          },
          {
            orderIndex: 7,
            sourceLanguage: "English",
            sourceText: "Yes, if you also want to apply for a payment plan due to financial hardship, you will need to complete a Financial Circumstances form.",
            expectedInterpretation: "അതെ, സാമ്പത്തിക ദുർഘടം കാരണം ഒരു പേയ്‌മെന്റ് പ്ലാൻ ആഗ്രഹിക്കുന്നുവെങ്കിൽ, ഒരു ഫിനാൻഷ്യൽ സർക്കംസ്റ്റൻസസ് ഫോം പൂരിപ്പിക്കണം.",
            keywords: ["payment plan", "financial hardship", "Financial Circumstances form"],
            topic: "legal",
            register: "formal",
            difficulty: "hard",
            scoringNotes: "Payment plan, financial hardship, and form name all critical.",
          },
          {
            orderIndex: 8,
            sourceLanguage: "Malayalam",
            sourceText: "ഞാൻ ഇതിനെ ഒറ്റയ്ക്ക് കൈകാര്യം ചെയ്യാൻ ആഗ്രഹിക്കുന്നില്ല. ഒരു ലീഗൽ ഏയ്ഡ് ഉണ്ടോ?",
            expectedInterpretation: "I do not want to handle this alone. Is there a legal aid available?",
            keywords: ["legal aid", "alone"],
            topic: "legal",
            register: "formal",
            difficulty: "easy",
            scoringNotes: "Legal aid concept and reluctance to handle alone.",
          },
        ],
      },
    ],
  },

  // ─── MOCK TEST 5: Immigration / Settlement ────────────────────────────────
  {
    title: "Mock Test 5 — Immigration & Settlement",
    description: "Visa enquiry, citizenship, and settlement services.",
    orderIndex: 5,
    dialogues: [
      {
        orderIndex: 1,
        title: "Dialogue 1 — Visa Enquiry",
        topic: "immigration",
        totalWords: 290,
        segments: [
          {
            orderIndex: 1,
            sourceLanguage: "English",
            sourceText: "Department of Home Affairs. This is Kylie speaking. How can I assist you today?",
            expectedInterpretation: "ഡിപ്പാർട്ട്‌മെന്റ് ഓഫ് ഹോം അഫയേഴ്‌സ്. ഞാൻ കൈലി ആണ്. ഇന്ന് ഞാൻ നിങ്ങൾക്ക് എങ്ങനെ സഹായിക്കാം?",
            keywords: ["Department of Home Affairs", "Kylie"],
            topic: "immigration",
            register: "formal",
            difficulty: "easy",
            scoringNotes: "Department name and officer's name must appear.",
          },
          {
            orderIndex: 2,
            sourceLanguage: "Malayalam",
            sourceText: "എനിക്ക് 482 വർക്ക് വിസ ഉണ്ട്. ഞാൻ ആ വിസ ഒരു 186 സ്ഥിര താമസ വിസ ആക്കി മാറ്റണം.",
            expectedInterpretation: "I have a 482 work visa. I want to change it to a 186 permanent residence visa.",
            keywords: ["482", "186", "permanent residence"],
            topic: "immigration",
            register: "formal",
            difficulty: "hard",
            scoringNotes: "Both visa subclass numbers (482, 186) and permanent residence must be exact.",
          },
          {
            orderIndex: 3,
            sourceLanguage: "English",
            sourceText: "To apply for a subclass 186 visa under the Employer Nomination Scheme, your employer must nominate you. Have they done so?",
            expectedInterpretation: "എംപ്ലോയർ നോമിനേഷൻ സ്‌കീം വഴി 186 സബ്‌ക്ലാസ് വിസ അപ്ലൈ ചെയ്യാൻ, നിങ്ങളുടെ തൊഴിലുടമ നിങ്ങളെ നോമിനേറ്റ് ചെയ്യണം. അവർ അത് ചെയ്‌തിട്ടുണ്ടോ?",
            keywords: ["186", "Employer Nomination Scheme", "nominate"],
            topic: "immigration",
            register: "formal",
            difficulty: "hard",
            scoringNotes: "ENS scheme name and nomination concept are critical.",
          },
          {
            orderIndex: 4,
            sourceLanguage: "Malayalam",
            sourceText: "അതെ, തൊഴിലുടമ ഒരു ആഴ്ചക്ക് മുൻപ് നോമിനേഷൻ ഫയൽ ചെയ്തു. അപ്ലിക്കേഷൻ ഫീ എത്ര?",
            expectedInterpretation: "Yes, the employer filed the nomination one week ago. How much is the application fee?",
            keywords: ["one week ago", "nomination", "application fee"],
            topic: "immigration",
            register: "formal",
            difficulty: "medium",
            scoringNotes: "Timing one week ago and application fee question.",
          },
          {
            orderIndex: 5,
            sourceLanguage: "English",
            sourceText: "The current visa application charge for a subclass 186 is $4,770 for the primary applicant. Family members attract additional charges.",
            expectedInterpretation: "186 സബ്‌ക്ലാസ് വിസയ്ക്ക് നിലവിൽ പ്രാഥമിക അപേക്ഷകന് $4,770 ആണ് ആപ്ലിക്കേഷൻ ഫീ. കുടുംബ അംഗങ്ങൾക്ക് അധിക ചാർജ് ഉണ്ടാകും.",
            keywords: ["$4,770", "primary applicant", "family members", "additional charges"],
            topic: "immigration",
            register: "formal",
            difficulty: "hard",
            scoringNotes: "Amount $4,770 and additional family charges are both critical.",
          },
          {
            orderIndex: 6,
            sourceLanguage: "Malayalam",
            sourceText: "ഞാൻ ഭാര്യ ഉൾപ്പെടെ ഒരു കൂട്ടായ അപ്ലിക്കേഷൻ കൊടുക്കണം. ഇംഗ്ലീഷ് ടെസ്ട് ആവശ്യമുണ്ടോ?",
            expectedInterpretation: "I want to lodge a combined application including my wife. Is an English test required?",
            keywords: ["wife", "combined application", "English test"],
            topic: "immigration",
            register: "formal",
            difficulty: "medium",
            scoringNotes: "Combined application with spouse and English test question.",
          },
          {
            orderIndex: 7,
            sourceLanguage: "English",
            sourceText: "Yes. Both primary and secondary applicants must meet the Competent English standard, equivalent to IELTS 6.0 overall.",
            expectedInterpretation: "അതെ. പ്രാഥമിക, ദ്വിതീയ അപേക്ഷകർ ഇരുവരും IELTS 6.0 തത്തുല്യമായ കോംപ്റ്റന്റ് ഇംഗ്ലീഷ് നിലവാരം പൂർത്തിയാക്കണം.",
            keywords: ["Competent English", "IELTS 6.0", "primary", "secondary"],
            topic: "immigration",
            register: "formal",
            difficulty: "hard",
            scoringNotes: "Competent English standard and IELTS 6.0 both critical.",
          },
          {
            orderIndex: 8,
            sourceLanguage: "Malayalam",
            sourceText: "ഞങ്ങൾ ഇരുവർക്കും IELTS ഉണ്ട്. എല്ലാ ഡോക്യുമെന്റ് ലിസ്റ്റ് ഇമെയിൽ ആയി ലഭിക്കുമോ?",
            expectedInterpretation: "Both of us have IELTS. Can I receive the full document list by email?",
            keywords: ["IELTS", "document list", "email"],
            topic: "immigration",
            register: "formal",
            difficulty: "easy",
            scoringNotes: "Both have IELTS and email document list request.",
          },
        ],
      },
      {
        orderIndex: 2,
        title: "Dialogue 2 — Citizenship Application",
        topic: "immigration",
        totalWords: 275,
        segments: [
          {
            orderIndex: 1,
            sourceLanguage: "English",
            sourceText: "Welcome to the citizenship interview. I'm Officer Davidson. Please sit down and show me your passport.",
            expectedInterpretation: "സിറ്റിസൺഷിപ്പ് ഇന്റർവ്യൂ ൽ സ്വാഗതം. ഞാൻ ഓഫീസർ ഡേവിഡ്‌സൺ ആണ്. ദയവായി ഇരിക്കുക, നിങ്ങളുടെ പാസ്‌പോർട്ട് കാണിക്കുക.",
            keywords: ["citizenship interview", "Officer Davidson", "passport"],
            topic: "immigration",
            register: "formal",
            difficulty: "easy",
            scoringNotes: "Officer name, interview type, and request for passport.",
          },
          {
            orderIndex: 2,
            sourceLanguage: "Malayalam",
            sourceText: "ഇതാ. ഞാൻ ഓസ്‌ട്രേലിയയിൽ 5 വർഷമായി താമസിക്കുന്നു. 2 വർഷം മുൻപ് PR ലഭിച്ചു.",
            expectedInterpretation: "Here it is. I have been living in Australia for 5 years. I received PR 2 years ago.",
            keywords: ["5 years", "Australia", "PR", "2 years ago"],
            topic: "immigration",
            register: "formal",
            difficulty: "medium",
            scoringNotes: "Both durations 5 years total and PR 2 years ago are critical.",
          },
          {
            orderIndex: 3,
            sourceLanguage: "English",
            sourceText: "Good. The citizenship general eligibility requires 4 years in Australia, of which at least 12 months must be as a permanent resident.",
            expectedInterpretation: "നന്ന്. സിറ്റിസൺഷിപ്പ് പൊതു യോഗ്യതയ്ക്ക് ഓസ്‌ട്രേലിയയിൽ 4 വർഷം ആവശ്യമാണ്, അതിൽ ചുരുങ്ങിയത് 12 മാസം സ്ഥിര താമസക്കാരൻ ആയിരിക്കണം.",
            keywords: ["4 years", "12 months", "permanent resident"],
            topic: "immigration",
            register: "formal",
            difficulty: "hard",
            scoringNotes: "4-year and 12-month requirements both critical.",
          },
          {
            orderIndex: 4,
            sourceLanguage: "Malayalam",
            sourceText: "ഞാൻ ആ യോഗ്യത പൂർത്തിയാക്കി. ഒരു കാരണം കൊണ്ട് ഞാൻ 3 മാസം ഓസ്‌ട്രേലിയക്ക് പുറത്ത് ആയിരുന്നു.",
            expectedInterpretation: "I have completed that eligibility. For one reason I was outside Australia for 3 months.",
            keywords: ["3 months", "outside Australia"],
            topic: "immigration",
            register: "formal",
            difficulty: "medium",
            scoringNotes: "Absence period 3 months and cause must be clear.",
          },
          {
            orderIndex: 5,
            sourceLanguage: "English",
            sourceText: "Absences of up to 12 months in the preceding 4 years are generally permitted for citizenship purposes.",
            expectedInterpretation: "സിറ്റിസൺഷിപ്പ് ആവശ്യങ്ങൾക്കായി കഴിഞ്ഞ 4 വർഷത്തിൽ 12 മാസം വരെ ഓസ്‌ട്രേലിയക്ക് പുറത്ത് ആകാൻ സാധാരണ അനുവദനീയമാണ്.",
            keywords: ["12 months", "4 years", "absences", "permitted"],
            topic: "immigration",
            register: "formal",
            difficulty: "hard",
            scoringNotes: "Both numbers and the permission rule.",
          },
          {
            orderIndex: 6,
            sourceLanguage: "Malayalam",
            sourceText: "നന്ന്. ഒരു ഓസ്‌ട്രേലിയൻ ഇന്റഗ്രേഷൻ ടെസ്ട് ഉണ്ടോ?",
            expectedInterpretation: "Good. Is there an Australian integration test?",
            keywords: ["Australian integration test"],
            topic: "immigration",
            register: "formal",
            difficulty: "easy",
            scoringNotes: "Test name must be rendered.",
          },
          {
            orderIndex: 7,
            sourceLanguage: "English",
            sourceText: "Yes. You must pass the Australian Citizenship Test which covers Australian values, history, and government. It is computer-based.",
            expectedInterpretation: "അതെ. ഓസ്‌ട്രേലിയൻ മൂല്യങ്ങൾ, ചരിത്രം, ഭരണം എന്നിവ ഉൾക്കൊള്ളുന്ന ഓസ്‌ട്രേലിയൻ സിറ്റിസൺഷിപ്പ് ടെസ്ട് ജയിക്കണം. ഇത് കമ്പ്യൂട്ടർ-ബേസ്ഡ് ആണ്.",
            keywords: ["Australian Citizenship Test", "values", "history", "government", "computer-based"],
            topic: "immigration",
            register: "formal",
            difficulty: "medium",
            scoringNotes: "Test name, three content areas, and computer-based nature.",
          },
          {
            orderIndex: 8,
            sourceLanguage: "Malayalam",
            sourceText: "ഞാൻ തയ്യാറാണ്. ടെസ്ട് ഇന്ന് തന്നെ ആണോ?",
            expectedInterpretation: "I am ready. Is the test today itself?",
            keywords: ["ready", "test", "today"],
            topic: "immigration",
            register: "formal",
            difficulty: "easy",
            scoringNotes: "Readiness declaration and question about timing.",
          },
        ],
      },
    ],
  },

  // ─── MOCK TEST 6: Education & Social Services ─────────────────────────────
  {
    title: "Mock Test 6 — Education & Social Services",
    description: "School meetings and community support services.",
    orderIndex: 6,
    dialogues: [
      {
        orderIndex: 1,
        title: "Dialogue 1 — School Meeting",
        topic: "education",
        totalWords: 285,
        segments: [
          {
            orderIndex: 1,
            sourceLanguage: "English",
            sourceText: "Hello Mrs. Pillai. I'm Ms. Burton, your son Arjun's class teacher. Thank you for coming in today.",
            expectedInterpretation: "ഹലോ ശ്രീമതി പിള്ള. ഞാൻ Ms. ബർടൺ ആണ്, നിങ്ങളുടെ മകൻ അർജ്ജുന്റെ ക്ലാസ് ടീച്ചർ. ഇന്ന് വന്നതിന് നന്ദി.",
            keywords: ["Mrs. Pillai", "Ms. Burton", "Arjun"],
            topic: "education",
            register: "semi-formal",
            difficulty: "easy",
            scoringNotes: "All three names must be accurate.",
          },
          {
            orderIndex: 2,
            sourceLanguage: "Malayalam",
            sourceText: "നന്ദി. ടീച്ചർ ഒരു അടിയന്തിര കാര്യം ആണ് പറഞ്ഞത്. അർജ്ജുൻ ഒരു പ്രശ്‌നത്തിൽ ഉണ്ടോ?",
            expectedInterpretation: "Thank you. The teacher mentioned an urgent matter. Is Arjun in trouble?",
            keywords: ["urgent matter", "Arjun", "trouble"],
            topic: "education",
            register: "semi-formal",
            difficulty: "easy",
            scoringNotes: "Urgent framing and question about son.",
          },
          {
            orderIndex: 3,
            sourceLanguage: "English",
            sourceText: "Not exactly. But Arjun has been absent for 9 days this term without a medical certificate. The school requires documentation.",
            expectedInterpretation: "അങ്ങനെ അല്ല. പക്ഷേ അർജ്ജുൻ ഈ ടേമിൽ ഒരു മെഡിക്കൽ സർട്ടിഫിക്കറ്റ് ഇല്ലാതെ 9 ദിവസം ഹാജരല്ലായിരുന്നു. സ്കൂൾ ഡോക്യുമെന്റേഷൻ ആവശ്യപ്പെടുന്നു.",
            keywords: ["9 days", "medical certificate", "documentation"],
            topic: "education",
            register: "semi-formal",
            difficulty: "hard",
            scoringNotes: "Number 9 days and medical certificate are critical.",
          },
          {
            orderIndex: 4,
            sourceLanguage: "Malayalam",
            sourceText: "അർജ്ജുൻ ഒരു ആഴ്ചയായി ജലദോഷം ആണ്. ഡോക്ടർ കത്ത് ഞാൻ ഇന്ന് കൊണ്ടുവരാം.",
            expectedInterpretation: "Arjun has had a cold for one week. I will bring the doctor's letter today.",
            keywords: ["cold", "one week", "doctor's letter"],
            topic: "education",
            register: "semi-formal",
            difficulty: "easy",
            scoringNotes: "Duration one week, cold, and promise to bring letter.",
          },
          {
            orderIndex: 5,
            sourceLanguage: "English",
            sourceText: "Thank you. Also, Arjun is falling behind in maths. We recommend he attend a tutoring programme on Wednesday afternoons.",
            expectedInterpretation: "നന്ദി. കൂടാതെ, അർജ്ജുൻ ഗണിതത്തിൽ പിന്നോക്കം പോകുന്നു. ബുധനാഴ്ച ഉച്ചതിരിഞ്ഞ് ഒരു ട്യൂട്ടോറിംഗ് പ്രോഗ്രാമിൽ പങ്കെടുക്കാൻ ഞങ്ങൾ ശുപാർശ ചെയ്യുന്നു.",
            keywords: ["maths", "tutoring programme", "Wednesday afternoon"],
            topic: "education",
            register: "semi-formal",
            difficulty: "medium",
            scoringNotes: "Subject maths, day Wednesday, and programme recommendation.",
          },
          {
            orderIndex: 6,
            sourceLanguage: "Malayalam",
            sourceText: "ഈ ട്യൂട്ടോറിംഗ് ഫ്രീ ആണോ? ഞാൻ ഒരു സിംഗിൾ പേരന്റ് ആണ്.",
            expectedInterpretation: "Is this tutoring free? I am a single parent.",
            keywords: ["free", "single parent"],
            topic: "education",
            register: "semi-formal",
            difficulty: "easy",
            scoringNotes: "Cost question and personal context.",
          },
          {
            orderIndex: 7,
            sourceLanguage: "English",
            sourceText: "Yes, it is fully funded by the school. There is also a homework club every Tuesday that is open to all students.",
            expectedInterpretation: "അതെ, ഇത് പൂർണ്ണമായും സ്‌കൂൾ ഫണ്ട് ചെയ്‌തതാണ്. എല്ലാ ചൊവ്വാഴ്‌ചയും ഹോംവർക്ക് ക്ലബ് ഉണ്ട്, ഇത് എല്ലാ വിദ്യാർത്ഥികൾക്കും തുറന്നിട്ടുണ്ട്.",
            keywords: ["fully funded", "Tuesday", "homework club", "all students"],
            topic: "education",
            register: "semi-formal",
            difficulty: "medium",
            scoringNotes: "Free/funded, homework club, and Tuesday must all be rendered.",
          },
          {
            orderIndex: 8,
            sourceLanguage: "Malayalam",
            sourceText: "ഞാൻ ഇതിൽ സന്തോഷത്തോടെ ചേർക്കും. ടീച്ചർ ഇടക്കിടെ ഒരു അപ്‌ഡേറ്റ് ഇമെയിൽ ആയി തരുമോ?",
            expectedInterpretation: "I will happily enrol him in it. Will the teacher send occasional update emails?",
            keywords: ["enrol", "update", "email"],
            topic: "education",
            register: "semi-formal",
            difficulty: "easy",
            scoringNotes: "Enrolment commitment and email update request.",
          },
        ],
      },
      {
        orderIndex: 2,
        title: "Dialogue 2 — Social Services Support",
        topic: "social services",
        totalWords: 280,
        segments: [
          {
            orderIndex: 1,
            sourceLanguage: "English",
            sourceText: "Hello, welcome to Centrelink. How can I help you today?",
            expectedInterpretation: "ഹലോ, സെന്ററ്‌ലിങ്കിൽ സ്വാഗതം. ഇന്ന് ഞാൻ നിങ്ങൾക്ക് എങ്ങനെ സഹായിക്കാം?",
            keywords: ["Centrelink"],
            topic: "social services",
            register: "semi-formal",
            difficulty: "easy",
            scoringNotes: "Centrelink name must appear.",
          },
          {
            orderIndex: 2,
            sourceLanguage: "Malayalam",
            sourceText: "ഞാൻ ഒരു Parenting Payment ന് അപ്ലൈ ചെയ്യണം. ഞാൻ ഒരു കൊച്ചു കുഞ്ഞിന്റെ അമ്മ ആണ്.",
            expectedInterpretation: "I want to apply for a Parenting Payment. I am a mother of a young child.",
            keywords: ["Parenting Payment", "mother", "young child"],
            topic: "social services",
            register: "semi-formal",
            difficulty: "easy",
            scoringNotes: "Payment name Parenting Payment and context.",
          },
          {
            orderIndex: 3,
            sourceLanguage: "English",
            sourceText: "The Parenting Payment Single is available if you are a single parent with a child under 8. Are you single?",
            expectedInterpretation: "ഒരു 8 വയസ്സിൽ താഴെ കുഞ്ഞ് ഉള്ള ഒറ്റ രക്ഷകർത്താക്കൾക്ക് Parenting Payment Single ലഭ്യമാണ്. നിങ്ങൾ ഒറ്റക്കാണോ?",
            keywords: ["Parenting Payment Single", "8 years", "single parent"],
            topic: "social services",
            register: "semi-formal",
            difficulty: "medium",
            scoringNotes: "Age under 8 and single status question are critical.",
          },
          {
            orderIndex: 4,
            sourceLanguage: "Malayalam",
            sourceText: "അതെ, ഞാൻ ഒറ്റക്കാണ്. എന്റെ കുഞ്ഞിന് 3 വയസ്സ് ആണ്.",
            expectedInterpretation: "Yes, I am single. My child is 3 years old.",
            keywords: ["single", "3 years old"],
            topic: "social services",
            register: "semi-formal",
            difficulty: "easy",
            scoringNotes: "Child age 3 and single status.",
          },
          {
            orderIndex: 5,
            sourceLanguage: "English",
            sourceText: "You may be eligible. The current maximum fortnightly rate is $949.30. Your rate depends on your other income.",
            expectedInterpretation: "നിങ്ങൾ യോഗ്യ ആകാം. നിലവിൽ ഒരു ഫോർട്ട്‌നൈറ്റ്‌ലി പരമാവധി $949.30 ആണ്. നിങ്ങളുടെ നിരക്ക് മറ്റ് വരുമാനം അനുസരിച്ചിരിക്കും.",
            keywords: ["$949.30", "fortnightly", "income"],
            topic: "social services",
            register: "semi-formal",
            difficulty: "hard",
            scoringNotes: "Exact amount $949.30 and income test concept.",
          },
          {
            orderIndex: 6,
            sourceLanguage: "Malayalam",
            sourceText: "ഞാൻ കഴിഞ്ഞ ആഴ്ച ഒരു പാർട്ട്-ടൈം ജോലി തുടങ്ങി. ഒരു ആഴ്ചയിൽ $350 സമ്പാദിക്കുന്നു.",
            expectedInterpretation: "I started a part-time job last week. I earn $350 per week.",
            keywords: ["part-time", "last week", "$350", "per week"],
            topic: "social services",
            register: "semi-formal",
            difficulty: "medium",
            scoringNotes: "Income $350 per week and job timing both critical.",
          },
          {
            orderIndex: 7,
            sourceLanguage: "English",
            sourceText: "You must declare all income to Centrelink. Failure to report may result in a debt and possible penalties.",
            expectedInterpretation: "നിങ്ങൾ എല്ലാ വരുമാനവും സെന്ററ്‌ലിങ്കിൽ ഡിക്ലയർ ചെയ്യണം. റിപ്പോർട്ട് ചെയ്തില്ലെങ്കിൽ ഒരു കടം ഉണ്ടാകാം, ഒപ്പം ശിക്ഷ ഉണ്ടാകാൻ സാദ്ധ്യത ഉണ്ട്.",
            keywords: ["declare", "income", "debt", "penalties"],
            topic: "social services",
            register: "formal",
            difficulty: "hard",
            scoringNotes: "Declaration obligation, debt, and penalties must all be rendered.",
          },
          {
            orderIndex: 8,
            sourceLanguage: "Malayalam",
            sourceText: "ഞാൻ മനസ്സിലാക്കി. ഒരു Family Tax Benefit ഉം ഉണ്ടോ?",
            expectedInterpretation: "I understand. Is there also a Family Tax Benefit?",
            keywords: ["Family Tax Benefit"],
            topic: "social services",
            register: "semi-formal",
            difficulty: "easy",
            scoringNotes: "Specific payment name Family Tax Benefit.",
          },
        ],
      },
    ],
  },
];
