export const vocabularyTerms = [
  // HEALTH
  { english: "appointment", malayalam: "അപ്പോയിന്റ്മെന്റ്", romanisation: "appoyntment", domain: "health", simpleExplanation: "A scheduled meeting with a doctor", exampleSentenceEn: "I have a doctor's appointment at 3 pm.", exampleSentenceMl: "എനിക്ക് 3 മണിക്ക് ഡോക്ടർ അപ്പോയിന്റ്മെന്റ് ഉണ്ട്.", commonMistake: "Omitting the time when interpreting", difficulty: "easy" },
  { english: "prescription", malayalam: "പ്രിസ്ക്രിപ്ഷൻ / ഡോക്ടർ കുറിപ്പ്", romanisation: "preskripshan", domain: "health", simpleExplanation: "Doctor's written order for medication", exampleSentenceEn: "The doctor gave me a prescription for antibiotics.", exampleSentenceMl: "ഡോക്ടർ എനിക്ക് ആന്റിബയോട്ടിക്കിനുള്ള ഒരു പ്രിസ്ക്രിപ്ഷൻ കൊടുത്തു.", commonMistake: "Saying 'medicine paper' instead of prescription", difficulty: "easy" },
  { english: "referral", malayalam: "റഫറൽ", romanisation: "referral", domain: "health", simpleExplanation: "Letter directing patient to a specialist", exampleSentenceEn: "You need a referral from your GP to see a specialist.", exampleSentenceMl: "ഒരു സ്പെഷ്യലിസ്റ്റിനെ കാണാൻ GP യുടെ റഫറൽ ആവശ്യമാണ്.", commonMistake: "Translating as 'recommendation' losing medical context", difficulty: "medium" },
  { english: "blood pressure", malayalam: "രക്തസമ്മർദ്ദം", romanisation: "rakthasaMMarddam", domain: "health", simpleExplanation: "Pressure of blood against artery walls", exampleSentenceEn: "Your blood pressure is high.", exampleSentenceMl: "നിങ്ങളുടെ രക്തസമ്മർദ്ദം കൂടുതലാണ്.", commonMistake: "Borrowing 'blood pressure' without Malayalam equivalent", difficulty: "easy" },
  { english: "diabetes", malayalam: "പ്രമേഹം / ഡയബറ്റിസ്", romanisation: "prameham", domain: "health", simpleExplanation: "Condition with high blood sugar", exampleSentenceEn: "He has been diagnosed with Type 2 diabetes.", exampleSentenceMl: "അദ്ദേഹത്തിന് ടൈപ്പ് 2 പ്രമേഹം ഉണ്ടെന്ന് കണ്ടെത്തിയിട്ടുണ്ട്.", commonMistake: "Using English word only without prameham", difficulty: "easy" },
  { english: "cardiologist", malayalam: "ഹൃദ്രോഗ വിദഗ്ധൻ", romanisation: "hrudhroga vidagdhan", domain: "health", simpleExplanation: "Doctor specialising in heart conditions", exampleSentenceEn: "She was referred to a cardiologist.", exampleSentenceMl: "അവൾ ഒരു ഹൃദ്രോഗ വിദഗ്ധനിലേക്ക് റഫർ ചെയ്യപ്പെട്ടു.", commonMistake: "Using only 'heart doctor' missing formal term", difficulty: "medium" },
  { english: "anaesthesia", malayalam: "അനസ്‌തേഷ്യ / മരവിപ്പ്", romanisation: "anastheshia", domain: "health", simpleExplanation: "Medicine to prevent feeling pain during surgery", exampleSentenceEn: "You will be given general anaesthesia.", exampleSentenceMl: "നിങ്ങൾക്ക് ജനറൽ അനസ്‌തേഷ്യ നൽകും.", commonMistake: "Omitting type (general/local)", difficulty: "hard" },
  { english: "blood thinners", malayalam: "രക്തം നേർപ്പിക്കുന്ന മരുന്ന്", romanisation: "raktham nerppikkunna marnnu", domain: "health", simpleExplanation: "Medication that prevents blood clotting", exampleSentenceEn: "Do not take alcohol with blood thinners.", exampleSentenceMl: "രക്തം നേർപ്പിക്കുന്ന മരുന്നോടൊപ്പം മദ്യം കഴിക്കരുത്.", commonMistake: "Forgetting the meaning entirely", difficulty: "hard" },
  { english: "Medicare", malayalam: "മെഡിക്കെയർ", romanisation: "Medicare", domain: "health", simpleExplanation: "Australia's universal health insurance system", exampleSentenceEn: "Please bring your Medicare card.", exampleSentenceMl: "ദയവായി നിങ്ങളുടെ മെഡിക്കെയർ കാർഡ് കൊണ്ടുവരൂ.", commonMistake: "Explaining too much instead of just saying Medicare", difficulty: "easy" },
  { english: "internal bleeding", malayalam: "ആന്തരിക രക്തസ്രാവം", romanisation: "aantharika rakthasraavam", domain: "health", simpleExplanation: "Bleeding inside the body", exampleSentenceEn: "Alcohol increases risk of internal bleeding.", exampleSentenceMl: "മദ്യം ആന്തരിക രക്തസ്രാവ സാദ്ധ്യത കൂട്ടുന്നു.", commonMistake: "Saying only 'bleeding inside' without correct Malayalam", difficulty: "hard" },
  { english: "discharge", malayalam: "ഡിസ്ചാർജ് / ആശുപത്രി വിടൽ", romanisation: "discharge", domain: "health", simpleExplanation: "Release from hospital", exampleSentenceEn: "You will be discharged today.", exampleSentenceMl: "ഇന്ന് നിങ്ങൾക്ക് ഡിസ്ചാർജ് ആകാം.", commonMistake: "Not capturing the hospital release context", difficulty: "easy" },
  { english: "chest pain", malayalam: "നെഞ്ചുവേദന", romanisation: "nenjuvEdhana", domain: "health", simpleExplanation: "Pain in the chest area", exampleSentenceEn: "I have had chest pain for a week.", exampleSentenceMl: "ഒരാഴ്ചയായി എനിക്ക് നെഞ്ചുവേദന ഉണ്ട്.", commonMistake: "Saying 'heart pain' which implies heart attack", difficulty: "easy" },
  { english: "dizziness", malayalam: "തലകറക്കം", romanisation: "thalakkarakkam", domain: "health", simpleExplanation: "Feeling of spinning or lightheadedness", exampleSentenceEn: "I feel dizzy sometimes.", exampleSentenceMl: "ചിലപ്പോൾ എനിക്ക് തലകറക്കം തോന്നുന്നു.", commonMistake: "Using vertigo (ചക്കര) when dizziness (തലകറക്കം) is meant", difficulty: "easy" },
  { english: "shortness of breath", malayalam: "ശ്വാസതടസ്സം", romanisation: "shvaasathadassam", domain: "health", simpleExplanation: "Difficulty breathing", exampleSentenceEn: "Do you have shortness of breath?", exampleSentenceMl: "നിങ്ങൾക്ക് ശ്വാസതടസ്സം ഉണ്ടോ?", commonMistake: "Omitting this symptom when multiple symptoms are given", difficulty: "medium" },
  { english: "follow-up appointment", malayalam: "ഫോളോ-അപ്പ് അപ്പോയിന്റ്മെന്റ്", romanisation: "follow-up appoyntment", domain: "health", simpleExplanation: "Second visit to check on progress", exampleSentenceEn: "Your follow-up is in two weeks.", exampleSentenceMl: "നിങ്ങളുടെ ഫോളോ-അപ്പ് രണ്ടാഴ്ച കഴിഞ്ഞ് ആണ്.", commonMistake: "Saying 'next appointment' without follow-up context", difficulty: "medium" },

  // LEGAL
  { english: "statutory declaration", malayalam: "സ്റ്റാറ്റ്യൂട്ടറി ഡിക്ലറേഷൻ", romanisation: "statutory declaration", domain: "legal", simpleExplanation: "Legally binding written statement", exampleSentenceEn: "You must attach a statutory declaration.", exampleSentenceMl: "നിങ്ങൾ ഒരു സ്റ്റാറ്റ്യൂട്ടറി ഡിക്ലറേഷൻ ചേർക്കണം.", commonMistake: "Translating as 'official document' losing legal specificity", difficulty: "hard" },
  { english: "default judgment", malayalam: "ഡിഫോൾട്ട് ജഡ്ജ്‌മെന്റ്", romanisation: "default judgment", domain: "legal", simpleExplanation: "Court ruling given when defendant does not respond", exampleSentenceEn: "A default judgment was entered against you.", exampleSentenceMl: "നിങ്ങൾക്കെതിരെ ഒരു ഡിഫോൾട്ട് ജഡ്ജ്‌മെന്റ് നൽകിയിട്ടുണ്ട്.", commonMistake: "Omitting the 'default' aspect", difficulty: "hard" },
  { english: "adverse action", malayalam: "ആഡ്‌വേഴ്സ് ആക്ഷൻ", romanisation: "adverse action", domain: "legal", simpleExplanation: "Illegal retaliation against an employee", exampleSentenceEn: "Dismissal for complaining is adverse action.", exampleSentenceMl: "ആരോപണം ഫയൽ ചെയ്തതിനുള്ള ഒഴിവാക്കൽ ആഡ്‌വേഴ്സ് ആക്ഷൻ ആണ്.", commonMistake: "Not knowing this legal concept", difficulty: "hard" },
  { english: "subpoena", malayalam: "സബ്‌പ്പൊയ്ന / കോടതി സമൻ", romanisation: "subpoena", domain: "legal", simpleExplanation: "Court order requiring someone to appear", exampleSentenceEn: "You have been issued a subpoena.", exampleSentenceMl: "നിങ്ങൾക്ക് ഒരു സബ്‌പ്പൊയ്ന ഇഷ്യൂ ചെയ്‌തിരിക്കുന്നു.", commonMistake: "Saying 'court letter' which is too vague", difficulty: "hard" },
  { english: "bail", malayalam: "ജാമ്യം", romanisation: "jaamyam", domain: "legal", simpleExplanation: "Release from custody before trial with conditions", exampleSentenceEn: "He was granted bail of $5,000.", exampleSentenceMl: "അദ്ദേഹത്തിന് $5,000 ജാമ്യം ലഭിച്ചു.", commonMistake: "Confusing bail with fine", difficulty: "medium" },
  { english: "legal aid", malayalam: "ലീഗൽ ഏയ്ഡ് / നിയമ സഹായം", romanisation: "legal aid", domain: "legal", simpleExplanation: "Free or subsidised legal help for those who can't afford it", exampleSentenceEn: "You can apply for legal aid.", exampleSentenceMl: "നിങ്ങൾക്ക് ലീഗൽ ഏയ്ഡ് ന് അപ്ലൈ ചെയ്യാം.", commonMistake: "Not specifying it is free/government-funded", difficulty: "medium" },
  { english: "plaintiff", malayalam: "വാദി", romanisation: "vaadhi", domain: "legal", simpleExplanation: "Person who brings a case to court", exampleSentenceEn: "The plaintiff claims damages.", exampleSentenceMl: "വാദി നഷ്ടപരിഹാരം ആവശ്യപ്പെടുന്നു.", commonMistake: "Confusing plaintiff and defendant", difficulty: "hard" },
  { english: "defendant", malayalam: "പ്രതി / എതിർ കക്ഷി", romanisation: "prathi", domain: "legal", simpleExplanation: "Person accused or sued in court", exampleSentenceEn: "The defendant denied the charges.", exampleSentenceMl: "പ്രതി ആരോപണങ്ങൾ നിരസിച്ചു.", commonMistake: "Using plaintiff/defendant interchangeably", difficulty: "medium" },
  { english: "warrant", malayalam: "വാറന്റ്", romanisation: "warrant", domain: "legal", simpleExplanation: "Official authorisation for police to act", exampleSentenceEn: "Police have a warrant to search the house.", exampleSentenceMl: "വീട് തിരഞ്ഞ് ഒഴിവാക്കാൻ പൊലീസിന് ഒരു വാറന്റ് ഉണ്ട്.", commonMistake: "Not distinguishing arrest warrant from search warrant", difficulty: "medium" },

  // IMMIGRATION
  { english: "permanent residency", malayalam: "സ്ഥിര താമസ അനുമതി", romanisation: "sthira thaamasa anumathi", domain: "immigration", simpleExplanation: "Right to live in Australia permanently", exampleSentenceEn: "She applied for permanent residency.", exampleSentenceMl: "അവൾ സ്ഥിര താമസ അനുമതിക്ക് അപ്ലൈ ചെയ്തു.", commonMistake: "Saying citizenship instead of permanent residency", difficulty: "medium" },
  { english: "visa subclass", malayalam: "വിസ സബ്ക്ലാസ്", romanisation: "visa subclass", domain: "immigration", simpleExplanation: "Specific category of Australian visa", exampleSentenceEn: "I am on a subclass 482 visa.", exampleSentenceMl: "ഞാൻ 482 സബ്ക്ലാസ് വിസയിൽ ആണ്.", commonMistake: "Omitting the subclass number", difficulty: "medium" },
  { english: "nomination", malayalam: "നോമിനേഷൻ", romanisation: "nomination", domain: "immigration", simpleExplanation: "Employer's formal support for visa applicant", exampleSentenceEn: "Your employer must file a nomination.", exampleSentenceMl: "നിങ്ങളുടെ തൊഴിലുടമ ഒരു നോമിനേഷൻ ഫയൽ ചെയ്യണം.", commonMistake: "Translating as 'recommendation' missing technical meaning", difficulty: "hard" },
  { english: "bridging visa", malayalam: "ബ്രിഡ്ജിംഗ് വിസ", romanisation: "bridging visa", domain: "immigration", simpleExplanation: "Temporary visa while main visa is processed", exampleSentenceEn: "You will be on a bridging visa during processing.", exampleSentenceMl: "പ്രോസസ്സിംഗ് സമയത്ത് നിങ്ങൾ ഒരു ബ്രിഡ്ജിംഗ് വിസയിൽ ആയിരിക്കും.", commonMistake: "Not knowing this is a specific visa type", difficulty: "hard" },
  { english: "character requirement", malayalam: "സ്വഭാവ ആവശ്യകത", romanisation: "svabhaava aavashyakatha", domain: "immigration", simpleExplanation: "Good conduct requirement for visa/citizenship", exampleSentenceEn: "You must meet the character requirement.", exampleSentenceMl: "നിങ്ങൾ സ്വഭാവ ആവശ്യകത പൂർത്തിയാക്കണം.", commonMistake: "Vague interpretation of 'good character'", difficulty: "hard" },
  { english: "migration agent", malayalam: "മൈഗ്രേഷൻ ഏജന്റ്", romanisation: "migration agent", domain: "immigration", simpleExplanation: "Registered professional who assists with visa applications", exampleSentenceEn: "Consult a registered migration agent.", exampleSentenceMl: "ഒരു രജിസ്ട്രേഡ് മൈഗ്രേഷൻ ഏജന്റിനെ സമീപിക്കുക.", commonMistake: "Not specifying 'registered'", difficulty: "medium" },

  // EMPLOYMENT
  { english: "redundancy", malayalam: "മിച്ചം / റിഡൻഡൻസി", romanisation: "redundancy", domain: "employment", simpleExplanation: "Job loss because position no longer exists", exampleSentenceEn: "He received a redundancy payment.", exampleSentenceMl: "അദ്ദേഹത്തിന് റിഡൻഡൻസി പേയ്‌മെന്റ് ലഭിച്ചു.", commonMistake: "Confusing redundancy with unfair dismissal", difficulty: "hard" },
  { english: "payslip", malayalam: "ശമ്പള വ്യതിയാനം / പേ സ്ലിപ്പ്", romanisation: "paslip", domain: "employment", simpleExplanation: "Document showing earnings and deductions", exampleSentenceEn: "Please provide your last three payslips.", exampleSentenceMl: "ദയവായി നിങ്ങളുടെ അവസാനത്തെ മൂന്ന് പേ സ്ലിപ്പ് നൽകൂ.", commonMistake: "Saying 'salary proof' instead of payslip", difficulty: "easy" },
  { english: "casual employee", malayalam: "കാഷ്വൽ ജീവനക്കാരൻ", romanisation: "casual jeevanakkaaran", domain: "employment", simpleExplanation: "Worker without guaranteed regular hours", exampleSentenceEn: "Casual employees do not have paid leave.", exampleSentenceMl: "കാഷ്വൽ ജീവനക്കാർക്ക് ശമ്പളത്തോടുകൂടിയ അവധി ഇല്ല.", commonMistake: "Confusing casual with part-time", difficulty: "medium" },
  { english: "annual leave", malayalam: "വാർഷിക അവധി", romanisation: "vaarshika avadhi", domain: "employment", simpleExplanation: "Paid yearly vacation entitlement", exampleSentenceEn: "You are entitled to 4 weeks of annual leave.", exampleSentenceMl: "നിങ്ങൾക്ക് 4 ആഴ്ചത്തെ വാർഷിക അവധിക്ക് അർഹതയുണ്ട്.", commonMistake: "Saying 'holiday' without specifying annual entitlement", difficulty: "easy" },
  { english: "enterprise agreement", malayalam: "എന്റർപ്രൈസ് അഗ്രിമെന്റ്", romanisation: "enterprise agreement", domain: "employment", simpleExplanation: "Negotiated pay and conditions for a specific workplace", exampleSentenceEn: "Your pay is set by an enterprise agreement.", exampleSentenceMl: "നിങ്ങളുടെ ശമ്പളം ഒരു എന്റർപ്രൈസ് അഗ്രിമെന്റ് വഴി നിശ്ചയിക്കുന്നു.", commonMistake: "Saying 'work contract' which is different", difficulty: "hard" },
  { english: "superannuation", malayalam: "സൂപ്പർ / സൂപ്പർആനൂവേഷൻ", romanisation: "superannuation", domain: "employment", simpleExplanation: "Compulsory retirement savings in Australia", exampleSentenceEn: "Employers must pay 11% superannuation.", exampleSentenceMl: "തൊഴിലുടമ 11% സൂപ്പർആനൂവേഷൻ അടക്കണം.", commonMistake: "Not knowing the Australian context", difficulty: "medium" },

  // EDUCATION
  { english: "enrolment", malayalam: "ചേർക്കൽ / എൻറോൾമെന്റ്", romanisation: "enrollment", domain: "education", simpleExplanation: "Process of registering for school/course", exampleSentenceEn: "Enrolment is open until March 31.", exampleSentenceMl: "മാർച്ച് 31 വരെ ചേർക്കൽ തുറന്നിരിക്കും.", commonMistake: "Confusing enrolment with attendance", difficulty: "easy" },
  { english: "tutoring", malayalam: "ട്യൂഷൻ / ട്യൂട്ടോറിംഗ്", romanisation: "tuition", domain: "education", simpleExplanation: "Extra teaching help for a student", exampleSentenceEn: "The school offers free tutoring.", exampleSentenceMl: "സ്‌കൂൾ സൗജന്യ ട്യൂഷൻ നൽകുന്നു.", commonMistake: "Not rendering 'free' qualifier", difficulty: "easy" },
  { english: "medical certificate", malayalam: "മെഡിക്കൽ സർട്ടിഫിക്കറ്റ്", romanisation: "medical certificate", domain: "education", simpleExplanation: "Doctor's letter proving illness", exampleSentenceEn: "Please provide a medical certificate for the absences.", exampleSentenceMl: "ഗൈർഹാജരുകൾക്ക് ഒരു മെഡിക്കൽ സർട്ടിഫിക്കറ്റ് നൽകൂ.", commonMistake: "Saying 'doctor's note' informally in formal context", difficulty: "easy" },
  { english: "absenteeism", malayalam: "ഹാജർ ഇല്ലായ്‌മ", romanisation: "hajar illayma", domain: "education", simpleExplanation: "Regular absence from school or work", exampleSentenceEn: "Chronic absenteeism affects learning.", exampleSentenceMl: "സ്ഥിരമായ ഹാജർ ഇല്ലായ്‌മ പഠനത്തെ ബാധിക്കുന്നു.", commonMistake: "Just saying 'absence' without the chronic pattern", difficulty: "medium" },

  // HOUSING
  { english: "bond", malayalam: "ബോണ്ട് / നിക്ഷേപം", romanisation: "bond", domain: "housing", simpleExplanation: "Security deposit paid at start of tenancy", exampleSentenceEn: "The bond was $2,000.", exampleSentenceMl: "ബോണ്ട് $2,000 ആയിരുന്നു.", commonMistake: "Translating bond as 'guarantee' in wrong context", difficulty: "easy" },
  { english: "landlord", malayalam: "ഭൂവുടമ / വീടുടമ", romanisation: "bhoovudama", domain: "housing", simpleExplanation: "Owner of rented property", exampleSentenceEn: "The landlord must arrange repairs.", exampleSentenceMl: "ഭൂവുടമ അറ്റകുറ്റപ്പണി ക്രമീകരിക്കണം.", commonMistake: "Saying 'owner' without landlord context", difficulty: "easy" },
  { english: "tenancy agreement", malayalam: "ലീസ് കരാർ / ടെനൻസി കരാർ", romanisation: "tenancy karar", domain: "housing", simpleExplanation: "Contract between landlord and tenant", exampleSentenceEn: "Sign the tenancy agreement before moving in.", exampleSentenceMl: "കയറുന്നതിനു മുൻപ് ടെനൻസി കരാർ ഒപ്പിടണം.", commonMistake: "Saying 'rent paper' informally", difficulty: "medium" },
  { english: "eviction notice", malayalam: "ഒഴിപ്പിക്കൽ നോട്ടീസ്", romanisation: "ozhippikkal notice", domain: "housing", simpleExplanation: "Legal notice to vacate property", exampleSentenceEn: "She received an eviction notice.", exampleSentenceMl: "അവൾക്ക് ഒരു ഒഴിപ്പിക്കൽ നോട്ടീസ് ലഭിച്ചു.", commonMistake: "Not conveying the legal urgency", difficulty: "medium" },
  { english: "routine inspection", malayalam: "നിത്യ ഇൻസ്പെക്ഷൻ", romanisation: "nithya inspection", domain: "housing", simpleExplanation: "Scheduled property check by landlord/agent", exampleSentenceEn: "We will conduct a routine inspection on Friday.", exampleSentenceMl: "വെള്ളിയാഴ്ച ഒരു നിത്യ ഇൻസ്പെക്ഷൻ നടത്തും.", commonMistake: "Rendering inspection without specifying it is routine/scheduled", difficulty: "easy" },

  // FINANCE
  { english: "interest rate", malayalam: "പലിശ നിരക്ക്", romanisation: "palisha niraku", domain: "finance", simpleExplanation: "Percentage charged on borrowed money", exampleSentenceEn: "The interest rate is 5.5% per year.", exampleSentenceMl: "പലിശ നിരക്ക് 5.5% ആണ്.", commonMistake: "Not rendering the percentage correctly", difficulty: "medium" },
  { english: "credit score", malayalam: "ക്രെഡിറ്റ് സ്കോർ", romanisation: "credit score", domain: "finance", simpleExplanation: "Rating of a person's creditworthiness", exampleSentenceEn: "A low credit score may affect your loan application.", exampleSentenceMl: "കുറഞ്ഞ ക്രെഡിറ്റ് സ്കോർ നിങ്ങളുടെ ലോൺ അപ്ലിക്കേഷനെ ബാധിക്കും.", commonMistake: "Not knowing this term exists in Malayalam context", difficulty: "medium" },
  { english: "hardship", malayalam: "ദുർഘടം / ബുദ്ധിമുട്ട്", romanisation: "durghaDam", domain: "finance", simpleExplanation: "Financial difficulty making payments impossible", exampleSentenceEn: "I am experiencing financial hardship.", exampleSentenceMl: "ഞാൻ സാമ്പത്തിക ദുർഘടം അനുഭവിക്കുന്നു.", commonMistake: "Using 'problem' (പ്രശ്നം) which is too vague", difficulty: "medium" },
  { english: "direct debit", malayalam: "ഡയറക്ട് ഡെബിറ്റ്", romanisation: "direct debit", domain: "finance", simpleExplanation: "Automatic payment from bank account", exampleSentenceEn: "Set up a direct debit for monthly payments.", exampleSentenceMl: "മാസ പേയ്‌മെന്റുകൾക്ക് ഒരു ഡയറക്ട് ഡെബിറ്റ് സജ്ജീകരിക്കൂ.", commonMistake: "Saying 'automatic transfer' losing technical term", difficulty: "hard" },
  { english: "tax return", malayalam: "ടാക്സ് റിട്ടേൺ", romanisation: "tax return", domain: "finance", simpleExplanation: "Annual filing to claim tax refund or declare tax owed", exampleSentenceEn: "You must lodge your tax return by October 31.", exampleSentenceMl: "ഒക്‌ടോബർ 31 ന് മുൻപ് ടാക്സ് റിട്ടേൺ ഫയൽ ചെയ്യണം.", commonMistake: "Saying 'tax paper' without the return concept", difficulty: "easy" },

  // INSURANCE
  { english: "claim", malayalam: "ക്ലൈം / ആവശ്യം", romanisation: "claim", domain: "insurance", simpleExplanation: "Request to insurance company for payment after loss", exampleSentenceEn: "I need to lodge an insurance claim.", exampleSentenceMl: "ഞാൻ ഒരു ഇൻഷുറൻസ് ക്ലൈം ഫയൽ ചെയ്യണം.", commonMistake: "Saying 'complaint' instead of claim", difficulty: "easy" },
  { english: "excess", malayalam: "എക്സ്സസ് / അധിക തുക", romanisation: "excess", domain: "insurance", simpleExplanation: "Amount you pay before insurance covers the rest", exampleSentenceEn: "Your excess is $500 for this claim.", exampleSentenceMl: "ഈ ക്ലൈമിന് നിങ്ങളുടെ എക്സ്സസ് $500 ആണ്.", commonMistake: "Not knowing excess means the deductible amount", difficulty: "hard" },
  { english: "premium", malayalam: "പ്രീമിയം", romanisation: "premium", domain: "insurance", simpleExplanation: "Regular payment for insurance coverage", exampleSentenceEn: "Your monthly premium is $120.", exampleSentenceMl: "നിങ്ങളുടെ മാസ പ്രീമിയം $120 ആണ്.", commonMistake: "Not rendering the amount that follows premium", difficulty: "easy" },
  { english: "policy", malayalam: "ഇൻഷുറൻസ് പോളിസി", romanisation: "insurance policy", domain: "insurance", simpleExplanation: "Insurance contract document", exampleSentenceEn: "Your policy covers flood damage.", exampleSentenceMl: "നിങ്ങളുടെ പോളിസി ഫ്ലഡ് നാശനഷ്ടം കവർ ചെയ്യുന്നു.", commonMistake: "Saying 'agreement' instead of policy", difficulty: "easy" },

  // CONSUMER AFFAIRS
  { english: "refund", malayalam: "തിരിച്ചടവ് / റിഫൻഡ്", romanisation: "refund", domain: "consumer", simpleExplanation: "Money returned for faulty goods or services", exampleSentenceEn: "I am entitled to a full refund.", exampleSentenceMl: "എനിക്ക് പൂർണ്ണ റിഫൻഡ് ലഭിക്കാൻ അർഹതയുണ്ട്.", commonMistake: "Saying 'return money' without refund context", difficulty: "easy" },
  { english: "consumer rights", malayalam: "ഉപഭോക്തൃ അവകാശങ്ങൾ", romanisation: "upabhokthru avakashangal", domain: "consumer", simpleExplanation: "Legal rights when buying goods or services", exampleSentenceEn: "Under consumer rights law, you can demand a replacement.", exampleSentenceMl: "ഉപഭോക്തൃ അവകാശ നിയമ പ്രകാരം, നിങ്ങൾക്ക് ഒരു പകരം ആവശ്യപ്പെടാം.", commonMistake: "Not specifying 'under law'", difficulty: "medium" },
  { english: "warranty", malayalam: "വാറന്റി / ഉറപ്പ്", romanisation: "warranty", domain: "consumer", simpleExplanation: "Guarantee that a product works properly", exampleSentenceEn: "The TV is under warranty for 2 years.", exampleSentenceMl: "ടിവി 2 വർഷത്തേക്ക് വാറന്റിക്ക് കീഴിൽ ആണ്.", commonMistake: "Confusing warranty and guarantee", difficulty: "easy" },
  { english: "Consumer Affairs Victoria", malayalam: "കൺസ്യൂമർ അഫേഴ്‌സ് വിക്ടോറിയ", romanisation: "Consumer Affairs Victoria", domain: "consumer", simpleExplanation: "Victorian government agency protecting consumers", exampleSentenceEn: "Lodge a complaint with Consumer Affairs Victoria.", exampleSentenceMl: "കൺസ്യൂമർ അഫേഴ്‌സ് വിക്ടോറിയയിൽ ഒരു പരാതി ഫയൽ ചെയ്യൂ.", commonMistake: "Saying 'consumer office' without full name", difficulty: "medium" },

  // SOCIAL SERVICES
  { english: "Centrelink", malayalam: "സെന്ററ്‌ലിങ്ക്", romanisation: "Centrelink", domain: "social_services", simpleExplanation: "Australian government social services agency", exampleSentenceEn: "You can apply at Centrelink.", exampleSentenceMl: "സെന്ററ്‌ലിങ്കിൽ അപ്ലൈ ചെയ്യാം.", commonMistake: "Saying 'government office' losing the specific name", difficulty: "easy" },
  { english: "Parenting Payment", malayalam: "Parenting Payment / രക്ഷകർത്തൃ ആനുകൂല്യം", romanisation: "Parenting Payment", domain: "social_services", simpleExplanation: "Government payment for parents of young children", exampleSentenceEn: "Single parents may receive the Parenting Payment.", exampleSentenceMl: "ഒറ്റ രക്ഷകർത്താക്കൾക്ക് Parenting Payment ലഭിക്കും.", commonMistake: "Not specifying it is for single or partnered parents", difficulty: "medium" },
  { english: "Family Tax Benefit", malayalam: "ഫാമിലി ടാക്സ് ബെനഫിറ്റ്", romanisation: "Family Tax Benefit", domain: "social_services", simpleExplanation: "Government payment to help families with children", exampleSentenceEn: "You may be eligible for Family Tax Benefit Part A.", exampleSentenceMl: "നിങ്ങൾ ഫാമിലി ടാക്സ് ബെനഫിറ്റ് പാർട്ട് A ക്ക് അർഹരായേക്കാം.", commonMistake: "Not knowing Part A and Part B are different", difficulty: "hard" },
  { english: "income test", malayalam: "വരുമാന പരിശോധന", romanisation: "varumana parishOdhana", domain: "social_services", simpleExplanation: "Check of income to determine benefit eligibility", exampleSentenceEn: "Payment depends on the income test.", exampleSentenceMl: "ആനുകൂല്യം വരുമാന പരിശോധനയെ ആശ്രയിക്കുന്നു.", commonMistake: "Saying 'income check' without formal meaning", difficulty: "medium" },
  { english: "JobSeeker", malayalam: "ജോബ്‌സീക്കർ", romanisation: "JobSeeker", domain: "social_services", simpleExplanation: "Unemployment payment from Centrelink", exampleSentenceEn: "I receive JobSeeker while looking for work.", exampleSentenceMl: "ജോലി തിരഞ്ഞ് കൊണ്ടിരിക്കുന്നതിനിടെ ഞാൻ ജോബ്‌സീക്കർ വാങ്ങുന്നു.", commonMistake: "Saying 'unemployment benefit' without specific name", difficulty: "easy" },

  // EXTRA HIGH-FREQUENCY TERMS
  { english: "interpreter", malayalam: "ഇന്റർപ്രിറ്റർ / വ്യാഖ്യാതാവ്", romanisation: "interpreter", domain: "general", simpleExplanation: "Person who translates spoken language", exampleSentenceEn: "Do you need an interpreter?", exampleSentenceMl: "നിങ്ങൾക്ക് ഒരു ഇന്റർപ്രിറ്റർ ആവശ്യമുണ്ടോ?", commonMistake: "Confusing interpreter (oral) with translator (written)", difficulty: "easy" },
  { english: "consent", malayalam: "സമ്മതം", romanisation: "sammadham", domain: "health", simpleExplanation: "Agreement to a medical procedure", exampleSentenceEn: "Please sign the consent form.", exampleSentenceMl: "ദയവായി സമ്മത ഫോം ഒപ്പിടൂ.", commonMistake: "Not rendering consent in medical context precisely", difficulty: "easy" },
  { english: "eligibility", malayalam: "അർഹത / യോഗ്യത", romanisation: "arhatha", domain: "general", simpleExplanation: "Meeting requirements to receive something", exampleSentenceEn: "You must meet eligibility criteria.", exampleSentenceMl: "നിങ്ങൾ അർഹതാ മാനദണ്ഡം പൂർത്തിയാക്കണം.", commonMistake: "Saying 'qualification' when eligibility is meant", difficulty: "medium" },
  { english: "assessment", malayalam: "മൂല്യനിർണ്ണയം / അസസ്‌മെന്റ്", romanisation: "mulyanirnNayam", domain: "general", simpleExplanation: "Evaluation of a person's situation or needs", exampleSentenceEn: "An assessment will be conducted.", exampleSentenceMl: "ഒരു അസസ്‌മെന്റ് നടത്തും.", commonMistake: "Using test/exam instead of assessment", difficulty: "medium" },
  { english: "penalty", malayalam: "ശിക്ഷ / പിഴ", romanisation: "shiksha / pizha", domain: "legal", simpleExplanation: "Punishment for breaking a rule", exampleSentenceEn: "Failure to report may result in a penalty.", exampleSentenceMl: "റിപ്പോർട്ട് ചെയ്യാത്തതിൽ ഒരു പിഴ ഉണ്ടാകും.", commonMistake: "Not distinguishing between financial penalty (പിഴ) and criminal penalty (ശിക്ഷ)", difficulty: "medium" },
];
